config/routes.rb
Rails.application.routes.draw do

  root 'home#front'


  get   '/login' => 'session#new', as: 'login'
  post  '/login' => 'session#create'
  get   '/logout' => 'session#destroy', as: 'logout'

  get   '/ps/:id/' => 'home#prospect_share', as: 'prospect_share'
  post   '/ps/l' => 'home#prospect_share_login', as: 'prospect_share_login'

  get   '/dashboard' => 'home#dashboard', as: 'dashboard'

  get   '/admin' => 'admin#index', as: 'admin'
  get   '/admin/new_bulk_upload' => 'admin#new_bulk_upload', as: 'new_bulk_upload'
  post   '/admin/new_bulk_upload' => 'admin#do_bulk_upload'
  get   '/admin/distributors' => 'admin#distributors_index', as: 'admin_distributors_index'
  get   '/admin/brands' => 'admin#brands_index', as: 'admin_brands_index'
  get   '/admin/retailers' => 'admin#retailers_index', as: 'admin_retailers_index'
  get   '/admin/orders/:group' => 'admin#orders_index', as: 'admin_orders_index'
  post   '/admin/orders/search/' => 'admin#orders_search', as: 'admin_orders_search'
  post   '/admin/orders/bc/' => 'admin#orders_by_company', as: 'admin_view_orders_by_company'
  get   '/admin/orders/search/pre/brands' => 'admin#orders_pre_search_brands', as: 'admin_orders_pre_search_brands'
  get   '/admin/orders/search/pre/buyers' => 'admin#orders_pre_search_buyers', as: 'admin_orders_pre_search_buyers'
  get   '/admin/order/d/:id/:confirm' => 'admin#order_destroy', as: 'admin_order_destroy'
  get   '/admin/distributor/:id' => 'admin#distributor_view', as: 'admin_distributor_view'
  get   '/admin/brand/:id' => 'admin#brand_view', as: 'admin_brand_view'
  get   '/admin/retailer/:id' => 'admin#retailer_view', as: 'admin_retailer_view'
  get   '/admin/order/:id' => 'admin#order_view', as: 'admin_order_view'
  post   '/admin/adduser/:id' => 'admin#add_user', as: 'admin_add_user'
  delete   '/admin/deleteuser/:id' => 'admin#delete_user', as: 'admin_delete_user'


  # ORDERS
  resources :orders, only: [:show, :edit, :update, :destroy, :index]
  post   '/orders/search/' => 'orders#orders_search', as: 'orders_search'
  post   '/order/new' => 'orders#create', as: 'new_order'
  get   '/order/s/:id/:confirm' => 'orders#submit', as: 'submit_order'
  get   '/order/p/:id/:confirm' => 'orders#pending', as: 'pending_order'
  patch   '/order/p/:id/:confirm' => 'orders#pending'
  get   '/order/a/:id/:confirm' => 'orders#approve', as: 'approve_order'
  get   '/order/da/:id/:confirm' => 'orders#decline_approval', as: 'decline_approval_order'
  patch '/order/da/:id/:confirm' => 'orders#decline_approval'
  post  '/order/shipment/:id' => 'orders#shipment', as: 'order_shipment_info'
  # for non armor orders
  get   '/order/c/:id/:confirm' => 'orders#complete', as: 'complete_order'
  get   '/order/add/:id/:confirm' => 'orders#armor_disabled_delivered', as: 'armor_disabled_received_order'
  get   '/order/adc/:id/:confirm' => 'orders#armor_disabled_completed', as: 'armor_disabled_completed_order'
  # for order comments
  patch   '/order/comments/:id' => 'comments#update', as: 'order_update_comment'
  # order-calculator display
  get   'order/calculator/show/:id' => 'orders#show_calculator', as: 'show_order_calculator'

# PACKING LISTS

  get   '/admin/packinglists' => 'packing_lists#index', as: 'packing_lists'
  get   '/admin/packinglist/new' => 'packing_lists#new', as: 'new_packing_list'
  patch   '/admin/packinglist/update' => 'packing_lists#update', as: 'update_packing_list'

# comments
  resources :comments, only: [:create]

  # ARMOR PAYMENTS TESTING
  get   '/order/paid/:id/:confirm' => 'orders#paid', as: 'paid_order'
  get   '/order/delivered/:id/:confirm' => 'orders#delivered', as: 'delivered_order'

  resources :order_items, only: [:create, :edit, :update, :index]
  get   '/order/newitem/:product_id' => 'order_items#new', as: 'new_order_item'
  delete '/order/order_items/:o/:id' => 'order_items#destroy', as: 'delete_order_item'

  post   'order/charges/a/:order_id' => 'order_additional_charges#create', as: 'create_order_additional_charge'
  patch   'order/:order_id/charges/u/:id' => 'order_additional_charges#update', as: 'update_order_additional_charge'
  delete   'order/:order_id/charges/d/:id' => 'order_additional_charges#destroy', as: 'delete_order_additional_charge'

  # ARMOR PAYMENTS
  post  '/ap/complete' => 'armor_payments#complete_required', as: 'ap_complete_required'
  post  '/ap/create' => 'armor_payments#create_account', as: 'ap_create_account'
  post  '/ap/disable' => 'armor_payments#disable', as: 'ap_disable'
  post  '/ap/wh' => 'armor_payments#webhook'

  # "static" pages
  get  '/pages/:page' => 'pages#show'

  resources :articles, only: [:index, :show, :update, :destroy]
  get  '/article/view/:id' => 'articles#public_view', as: 'public_view_article'
  post  '/article/new/:type' => 'articles#create', as: 'create_article'
  post  '/article/fb/:id' => 'articles#featured_brand', as: 'article_featured_brand'
  delete  '/article/fb/:id/:fb_id' => 'articles#delete_featured_brand', as: 'delete_article_featured_brand'
  post  '/article/fp/:id' => 'articles#featured_product', as: 'article_featured_product'
  delete  '/article/fp/:id/:fp_id' => 'articles#delete_featured_product', as: 'delete_article_featured_product'
  delete  '/article/carousel/:id/' => 'articles#delete_carousel_photo', as: 'delete_article_carousel_photo'
  delete  '/article/tile/:id/' => 'articles#delete_tile_photo', as: 'delete_article_tile_photo'

  resources :article_photos, only: [:create]
  delete '/article_photos/:id/:article_id' => 'article_photos#destroy', as: 'delete_article_photo'

  resources :sectors, only: [:create, :update, :destroy]
  resources :subsectors, only: [:create, :update, :destroy]
  resources :channels, only: [:create, :update, :destroy]
  resources :company_sizes, only: [:create, :update, :destroy]
  resources :key_retailers, only: [:create, :update, :destroy]
  resources :trends, only: [:create, :update, :destroy]
  resources :countries, only: [:create, :update, :destroy]
  resources :channel_capacities, only: [:create, :update, :destroy]
  resources :brand_photos, only: [:create, :destroy]
  resources :contacts, only: [:index, :new, :create, :update, :destroy]
  resources :tags, only: [:new, :create, :destroy]

  post '/bulkupdate' => 'channel_capacities#bulkupdate', as: 'channel_capacity_bulkupdate'

  resources :displays, only: [:create, :update, :destroy]
  put '/displays/:id/:photo' => 'displays#update', as: 'display_delete'
  resources :distributor_brands, only: [:create, :update, :destroy]
  resources :trade_shows, only: [:create, :update, :destroy]
  resources :press_hits, only: [:create, :update, :destroy]
  delete '/press_hits/file_delete/:id' => 'press_hits#file_destroy', as: 'press_hits_file_delete'
  resources :products, only: [:create, :update, :destroy]
  get   'product/preview/:id' => 'products#preview', as: 'product_preview'
  resources :patents, only: [:create, :update, :destroy]
  resources :trademarks, only: [:create, :update, :destroy]
  resources :compliances, only: [:create, :update, :destroy]
  resources :export_countries, only: [:create, :update, :destroy]


  resources :product_photos, only: [:create]
  delete '/product_photos/:id' => 'product_photos#destroy', as: 'product_photo_delete'

  resources :library_documents, only: [:update, :create, :index]
  delete '/library_documents/:id' => 'library_documents#destroy', as: 'library_document_delete'



  # Deprecated
  # resources :sales_sizes, only: [:create, :update, :destroy]
  # resources :marketing_spends, only: [:create, :update, :destroy]
  
  resources :users, only: [:new, :create, :edit, :update, :destroy, :index]
  get    '/users/admin' => 'users#admin_index', as: 'users_admin'
  get    '/user/confirm/:token' => 'users#confirm_email', as: 'user_email_confirmation'
  patch    '/user/lu/:id' => 'users#limited_update', as: 'user_limited_update'

  get    '/distributor/edit' => 'distributors#edit', as: 'distributor'
  get    '/distributor/full_profile' => 'distributors#full_profile', as: 'distributor_full_profile'
  patch  '/distributor/edit' => 'distributors#update'
  patch  '/distributor_brands' => 'distributor_brands#update'
  patch  '/distributor/adminupdate/:id' => 'distributors#adminupdate', as: 'distributor_admin_update'
  delete '/distributor/validation/delitem' => 'distributors#validation_delete', as: 'distributor_validation_delete'

  get    '/retailer/edit' => 'retailers#edit', as: 'retailer'
  get    '/retailer/full_profile' => 'retailers#full_profile', as: 'retailer_full_profile'
  patch  '/retailer/edit' => 'retailers#update'
  patch  '/retailer/adminupdate/:id' => 'retailers#adminupdate', as: 'retailer_admin_update'
  delete '/retailer/validation/delitem' => 'retailers#validation_delete', as: 'retailer_validation_delete'


  # v2 public view
  get    '/brands' => 'brands#index', as: 'brands'
  get    '/brands/s/' => 'brands#search', as: 'search_brands'
  get    '/brand/view/:id' => 'brands#view', as: 'view_brand'
  get    '/brand/preview/:id' => 'brands#preview', as: 'preview_brand'

  get    '/retailer/view/:id' => 'retailers#view', as: 'view_retailer'
  get    '/distributor/view/:id' => 'distributors#view', as: 'view_distributor'

  # for brand editing
  get    '/brand/edit' => 'brands#edit', as: 'brand'
  get    '/brand/full_profile' => 'brands#full_profile', as: 'brand_full_profile'
  patch  '/brand/edit' => 'brands#update'
  patch  '/brand/adminupdate/:id' => 'brands#adminupdate', as: 'brand_admin_update'
  get    '/brand/subscribe' => 'brands#subscription', as: 'brand_subscription'

  # for article brand link
  get    '/brands/list' => 'brands#list', as: 'brand_list'
  # for article product link
  get    '/products/list' => 'products#list', as: 'product_list'

  get '/onboard/distributor/one' => 'onboard_distributor#one', as: 'onboard_distributor_one'
  get '/onboard/distributor/two' => 'onboard_distributor#two', as: 'onboard_distributor_two'

app/controllers/home_controller.rb
class HomeController < ApplicationController

	skip_before_action :require_login, only: [:front, :dashboard, :prospect_share, :prospect_share_login]
  	before_action only: [:dashboard] do
		check_subscription(area: 'restricted')
	end

	def front
		
		# for submenu
		@brand_chunk = Subsector.where(sector_id: Sector.where(name: 'Beauty / Personal Care').first.id).uniq { |p| p.name }.sort_by { |p| p.name }

		# for find links
		@trends = Trend.all.sort_by { |p| p.name }
		# @key_retailers = KeyRetailer.all.sort_by { |p| p.name }

		if @current_user
			if @current_user.administrator
				redirect_to admin_brands_index_url
			# else
			# 	redirect_to dashboard_url
			end
		else
			@newuser = User.new
			@newuser.build_contact
			render layout: "front"
		end
	end

	def login

	end

	def dashboard

		if @current_user

			@profile = @current_user.get_parent

			@current_orders = @profile.orders.current.count unless @current_user.brand
			@submitted_orders = @profile.orders.submitted.count
			@pending_orders = @profile.orders.pending.count
			@approved_orders = @profile.orders.approved.count
			@paid_orders = @profile.orders.paid.count
			@shipped_orders = @profile.orders.shipped.count
			@delivered_orders = @profile.orders.delivered.count
			@completed_orders = @profile.orders.completed.count
			@error_orders = @profile.orders.error.count
			@disputed_orders = @profile.orders.disputed.count
			# @active_orders = @profile.orders.active.count
			@active_orders = @current_user.brand ? @profile.orders.active_brand.count : @profile.orders.active.count

			@new_brands = Brand.activated.desc('c_at').limit(10)
			@updated_brands = Brand.activated.desc('u_at').limit(5)

			@recently_updated_orders = @profile.orders.active.desc('u_at').limit(10) if @current_user.brand

			products_with_photos = ProductPhoto.pluck(:photographable_id).uniq
			active_brands = Brand.activated.pluck(:id)
			@updated_products = Product.where(:brand_id.in => active_brands, :_id.in => products_with_photos).desc('u_at').desc('_id').limit(5)

			@adjustments = InventoryAdjustment.of_products(@profile.products.pluck(:id)).unfulfilled_requests if @current_user.brand
			# matches = @profile.matches
			# @unread_list = Array.new
			# matches.each do |m|
			# 	if m.messages.where(read: false, recipient: @current_user.type?).exists?
			# 		@unread_list << m
			# 	end
			# end
			# @incoming_requests_list = matches.where(accepted: false, initial_contact_by: @current_user.type_inverse?)
			# @outgoing_requests_list = matches.where(accepted: false, initial_contact_by: @current_user.type?)


			# case @current_user.type?
			# when "distributor"
			# 	@sector = @profile.sector_ids.to_s
		 #  	@gallery = ProductPhoto.where(photographable_type: "Product").shuffle[0..4]
			# 	@gallery_products = ProductPhoto.where(photographable_type: "Product").shuffle[0..11]

			# when "brand"

			# 	@all_matches = Distributor.in(sector_ids: @profile.sector_ids).excludes(country_of_origin: "", export_countries: nil)
			# 	@countries_of_distribution = Array.new
			# 	@all_matches.each do |m|
			# 		if !m.export_countries.blank?
			# 			@countries_of_distribution = (@countries_of_distribution << m.export_countries.pluck(:country)).flatten!
			# 		end
			# 	end
			# 	@country_of_distribution = @countries_of_distribution.uniq!
				
			# end
		end
		
	end

	def prospect_share
		if @share_id = params[:id]
			if @current_user
				if @current_user.brand
					# currently can only share brands, so only visible by distributors
					redirect_to dashboard_url and return
				elsif @current_user.distributor
					redirect_to view_match_url(@share_id, 'na') and return
				elsif @current_user.administrator
					redirect_to admin_brand_view_url(@share_id) and return
				end
			end
		else
			redirect_to root and return
		end
		render layout: "front"
	end

	def prospect_share_login

		unless params[:email].empty?
			if (@share_id = params[:share_id]) && (@email = params[:email])
				if User.where(email: @email).exists?
					@has_a_login = true
				else
			    @newuser = User.new
			    @newuser.build_contact 
				end
			else
				redirect_to root
			end
		end

		respond_to do |format|
			format.html
			format.js
		end 

	end


	private

	def is_a_brand?
		return true if @current_user && @current_user.brand
	end
end

app/helpers/home_helper.rb
module HomeHelper

	def get_share_type(id)
		if Brand.find(id)
			return 'brand'
		elsif Distributor.find(id)
			return 'distributor'
		else
			return nil
		end
	end
	
	def get_main_article
		article = Article.active.order_by(:date.desc).first
		return article
	end

	def get_sub_articles
		articles = Article.active.order_by(:date.desc).skip(1)
		return articles
	end

	def get_carousel_articles
		articles = Article.active.carousel.order_by(:date.desc)
		return articles
	end

	def get_grid_articles
		articles = Article.active.tiles_articles.no_carousel.order_by(:date.desc)
		return articles
	end

	def get_remaining_articles
		articles = Article.active.order_by(:date.desc).skip(6)
		return articles
	end

	def order_status(order)
		status = order.status
		case status
		when "open"
			return "<span id='#{status.downcase}'>STARTED</span> on #{order.c_at.strftime('%b %d, %Y')}"
		when "submitted"
			return "<span id='#{status.downcase}'>SUBMITTED</span> on #{order.submission_date.strftime('%b %d, %Y')}"
		when "pending"
			return "<span id='#{status.downcase}'>PENDING</span> on #{order.pending_date_array.first.strftime('%b %d, %Y')}"
		when "approved"
			return "<span id='#{status.downcase}'>APPROVED</span> on #{order.approved_date.strftime('%b %d, %Y')}"
		when "paid"
			return "<span id='#{status.downcase}'>PAYMENT IN ESCROW</span> on #{order.paid_date.strftime('%b %d, %Y')}"
		when "shipped"
			return "<span id='#{status.downcase}'>SHIPPED</span> on #{order.shipped_date.strftime('%b %d, %Y')}"
		when "delivered"
			return "<span id='#{status.downcase}'>DELIVERED</span> on #{order.delivered_date.strftime('%b %d, %Y')}"
		when "completed"
			if order.armor_enabled?
				return "<span id='#{status.downcase}'>COMPLETED (PAYMENT RELEASED)</span> on #{order.completed_date.strftime('%b %d, %Y')}"
			else
				return "<span id='#{status.downcase}'>COMPLETED</span> on #{order.completed_date.strftime('%b %d, %Y')}"
			end
		when "error"
			return "<span id='#{status.downcase}'>IN ERROR</span> on #{order.error_date.strftime('%b %d, %Y')}"
		when "disputed"
			return "<span id='#{status.downcase}'>IN DISPUTE</span> on #{order.disputed_date.strftime('%b %d, %Y')}"

		end
	end

	def get_onboard_stage(company:, user:)
		return company.onboard_stage(user)
	end

	def get_onboard_stage_class(current_stage:,stage:)

		if current_stage == 1
			case stage
			when 1
				return "class=active"
			else
				return nil
			end
		elsif current_stage == 2
			case stage
			when 1
				return "class=done"
			when 2
				return "class=active"
			else
				return nil
			end 
		elsif current_stage == 3
			case stage
			when 1..2
				return "class=done"
			when 3
				return "class=active"
			else
				return nil
			end
		elsif current_stage == 4
			case stage
			when 1..3
				return "class=done"
			when 4
				return "class=active"
			else
				return nil
			end
		elsif current_stage == 5
			case stage
			when 1..4
				return "class=done"
			when 5
				return "class=active"
			else
				return nil
			end
		else 
			return "class=done"
		end
		
	end

	def show_to_do?
		if @adjustments.present?
			return true
		end
	end

end

app/views/home/_marketplace.html.erb
<div id="dashboard-marketplace-header">
	<%= image_tag "logo_header_marketplace.svg" %>
</div>

<div id="dashboard-marketplace-content">
<% if @current_user.distributor %>

	<div class="row collapse">
		<div class="small-12 columns text-left">
			<h2 class="dashboard-section-title">FIND NEW BRANDS</h2>
		</div><!--/.small-12-->
		<div class="small-12 columns">
			<div id="match-sectors-container">
				<div class="row">
					<div class="small-11 small-centered columns">
						<%= render partial: "matches/distributor_search_start" %>		
					</div><!--/.small-11 small-centered-->
				</div><!--/.row-->
			</div><!--/.match-map-container -->					
		</div><!--/.small-12-->
	</div>


<% elsif @current_user.brand %>

	<div class="row">
		<div class="small-12 columns">

		<h3 class="dashboard-section-title">FIND DISTRIBUTORS IN NEW MARKETS</h3>
		<div id="match-map-container">
			<div class="row show-for-small-only">
				<div class="small-12 columns">
					<h2>Find a Distributor for:</h2>		
				</div><!--/.small-12-->
			</div>
		
			<div id="match-search">
				<%= render partial: "matches/brand_search_start" %>
			</div>

		</div><!--/.match-map-container -->


		</div>
	</div>


<% end %>
</div>


<% if @current_user.distributor %>

	<% if @gallery %>
	<%= link_to gallery_url do %>
	<div id="dashboard-marketplace-header">
		<h3>Brand Gallery</h3>
	</div>
	<% end %>
	<div id="dashboard-marketplace-content">


	<div class="row collapse">
		<div class="small-11 small-centered columns">
			<div class="profile-content gallery-window">

				<ul class="medium-block-grid-3 small-block-grid-1">
					<% @gallery_products.each_with_index do |item, index| %>
						<li>
							<div class="gallery-item">
							<div class="row">
								<div class="small-12 columns">
									<%= link_to view_match_path(item.photographable.brand.id, "na") do %>
									<%= image_tag item.photo.url(:profile_tile) %>
									<% end %>
								</div><!--/.medium-5-->
							</div><!--/.row-->
							<div class="row collapse">
								<div class="small-12 columns text-center">
									<%= link_to view_match_path(item.photographable.brand.id, "na") do %>
									<h3><%= item.photographable.brand.company_name %><br><small><%= item.photographable.name %></small></h3>
									<% end %>
								</div>
							</div><!--/.row-->
							</div>
						</li>
					<% end %>
				</ul>

			</div>
		</div><!--/.small-12-->
	</div><!--/.row-->

	<div class="row">
		<div class="small-12 columns text-center">
	<%= link_to "MORE", gallery_url, class: "button tiny" %>
		</div><!--/.small-12-->
	</div><!--/.row-->

	</div>
	<% end %>
<% end %>

<%= link_to messages_url do %>
<div id="dashboard-marketplace-header">
	<h3>Messages</h3>
</div>
<% end %>
<div id="dashboard-marketplace-content">
	<%= render "message_center" %>
</div>


<% if @current_user.distributor %>


<%= link_to distributor_full_profile_url do %>
<div id="dashboard-marketplace-header">
	<h3>Profile</h3>
</div>
<% end %>

<div id="dashboard-marketplace-content">

			<div class="dashboard-profile-panel">

				<% percentp = check_distributor_public_profile %>
				<div class="row">
					<div class="medium-6 columns">
						<h3>Your <strong><%= link_to 'Public Profile', distributor_public_profile_url %></strong> is <%= percentp == 100 ? "" : "#{percentp}%" %> complete!
						<br>
						<small><span data-tooltip aria-haspopup="true" class="has-tip" title="Your public profile is viewable by all registered brands. It displays limited publicly available information including countries of distribution, year established, product sector and retail channels.">What is this?</span></small>
						</h3>
						
					</div><!--/.medium-6-->
					<div class="medium-6 columns">
						<div class="progress round small-12 <%= percentp == 100 ? "success" : "" %>">
						  <span class="meter text-center" style="width: <%= percentp %>%"><small class="text-right"></small></span>
						</div>
					</div><!--/.medium-6-->
				</div><!--/.row-->
				


				<hr>

				<% percentf = check_distributor_full_profile %>
				<div class="row">
					<div class="medium-6 columns">
						<h3>Your <strong><%= link_to 'Full Profile', distributor_full_profile_url %></strong> is <%= percentf == 100 ? "" : "#{percentf}%" %> complete!
						<br>
						<small><span data-tooltip aria-haspopup="true" class="has-tip radius" title="Your full profile is viewable only by premium brand subscribers. It contains information that helps brands determine whether your company is a good fit for their international expansion.">What is this?</span></small>
						</h3>
						
					</div><!--/.medium-6-->
					<div class="medium-6 columns">
						<div class="progress round small-12 <%= percentf == 100 ? "success" : "" %>">
						  <span class="meter text-center" style="width: <%= percentf %>%"><small class="text-right"></small></span>
						</div>
					</div><!--/.medium-6-->
				</div><!--/.row-->

				<hr>

				<div class="row">
					<div class="medium-6 columns">
						<h3>Your <strong><%= link_to 'RATING', distributor_full_profile_url %></strong> is <strong><%= (@current_user.distributor.rating + @current_user.distributor.completeness) / 2.0 %></strong> out of <strong>5</strong></h3>
						
						<small><span data-tooltip aria-haspopup="true" class="has-tip radius" title="Your ratings help identify you as a credible business partner. Your ratings are based on the completeness of your profile and verification of your company’s website, social media presence, business license and other factors. ">What is this?</span></small>
					</div><!--/.medium-6-->
					<div class="medium-6 columns">
						
						<%= render partial: "shared/profile/distributor_rating", locals: {d: @current_user.distributor} %>
						
					</div><!--/.medium-6-->
				</div><!--/.row-->

			</div>

</div>


<% elsif @current_user.brand %>

<%= link_to brand_full_profile_url do %>
<div id="dashboard-marketplace-header">
	<h3>Profile</h3>
</div>
<% end %>

<div id="dashboard-marketplace-content">

			<div class="dashboard-profile-panel">

				<% percentp = check_brand_public_profile %>
				<div class="row">
					<div class="medium-6 columns">
						<h3>Your <strong><%= link_to 'Public Profile', brand_public_profile_url %></strong> is <%= percentp == 100 ? "" : "#{percentp}%" %> complete!
						<br>
						<small><span data-tooltip aria-haspopup="true" class="has-tip" title="Your public profile is viewable by all registered distributors. It displays limited publicly available information, including your country of origin, year established, product sector and retail channels.">What is this?</span></small>
						</h3>
						
					</div><!--/.medium-6-->
					<div class="medium-6 columns">
						<div class="progress round small-12 <%= percentp == 100 ? "success" : "" %>">
						  <span class="meter text-center" style="width: <%= percentp %>%"><small class="text-right"></small></span>
						</div>
					</div><!--/.medium-6-->
				</div><!--/.row-->
				


				<hr>

				<% percentf = check_brand_full_profile(@profile) %>
				<div class="row">
					<div class="medium-6 columns">
						<h3>Your <strong><%= link_to 'Full Profile', brand_full_profile_url %></strong> is <%= percentf == 100 ? "" : "#{percentf}%" %> complete!
						<br>
						<small><span data-tooltip aria-haspopup="true" class="has-tip radius" title="Your full profile is viewable only by premium distributor subscribers. It contains information that helps distributors determine whether your brand would be a good fit for their market and their portfolio.">What is this?</span></small>
						</h3>
						
					</div><!--/.medium-6-->
					<div class="medium-6 columns">
						<div class="progress round small-12 <%= percentf == 100 ? "success" : "" %>">
						  <span class="meter text-center" style="width: <%= percentf %>%"><small class="text-right"></small></span>
						</div>
					</div><!--/.medium-6-->
				</div><!--/.row-->

			</div>

</div>
<% end %>

app/views/home/_new_company_tile.html.erb
<div class="index-item filtered">
<%= link_to preview_brand_url(brand), remote: true do %>
<div class="image">
	<% type, photo = index_item_photo(brand) %>
	<% if type == "logo" %>
		<%= image_tag photo %>
	<% else %>
		<%= image_tag photo %>
	<% end %>
</div>
<div class="name"><%= brand.company_name %></div>
<% end %>
</div><!--/.index-item-->

app/views/home/_onboard_buyer.html.erb
<h2 class="text-center">Complete your Profile to Reach More Brands</h2>
<% stage = get_onboard_stage(company:@current_user.company, user: @current_user)  %>
<ul class="onboard-flow-header" data-steps="4">
	
	<li <%= get_onboard_stage_class(current_stage: stage[:major], stage: 1)%>>
		<%= link_to_if_with_block stage[:major] == 1, onboard_url, {remote: true} do %>
			<span><%= image_tag "/images/create_profile.png" %></span>
		<% end %>
	</li>
	
	<li <%= get_onboard_stage_class(current_stage: stage[:major], stage: 2)%>>
		<%= link_to_if_with_block stage[:major] == 2, onboard_url, {remote: true} do %>
			<span><%= image_tag "/images/enable_payment.png" %><br>(BASIC)</span>
		<% end %>
	</li>
	
	<li <%= get_onboard_stage_class(current_stage: stage[:major], stage: 3)%>>
		<%= link_to_if_with_block stage[:major] == 3, onboard_url, {remote: true} do %>
			<span><%= image_tag "/images/introduce_yourself.png" %><br>(INTERMEDIATE)</span>
		<% end %>
	</li>		
	
	<li <%= get_onboard_stage_class(current_stage: stage[:major], stage: 4)%>>
		<%= link_to_if_with_block stage[:major] == 4, onboard_url, {remote: true} do %>
			<span><%= image_tag "/images/tell_us_more.png" %><br>(ADVANCED)</span>
		<% end %>
	</li>
</ul>