config/routes.rb
  delete '/order/order_items/:o/:id' => 'order_items#destroy', as: 'delete_order_item'

  post   'order/charges/a/:order_id' => 'order_additional_charges#create', as: 'create_order_additional_charge'
  patch   'order/:order_id/charges/u/:id' => 'order_additional_charges#update', as: 'update_order_additional_charge'
  delete   'order/:order_id/charges/d/:id' => 'order_additional_charges#destroy', as: 'delete_order_additional_charge'

  # ARMOR PAYMENTS
  post  '/ap/complete' => 'armor_payments#complete_required', as: 'ap_complete_required'
  post  '/ap/create' => 'armor_payments#create_account', as: 'ap_create_account'
  post  '/ap/disable' => 'armor_payments#disable', as: 'ap_disable'
  post  '/ap/wh' => 'armor_payments#webhook'

  # "static" pages
  get  '/pages/:page' => 'pages#show'

  resources :articles, only: [:index, :show, :update, :destroy]
  get  '/article/view/:id' => 'articles#public_view', as: 'public_view_article'
  post  '/article/new/:type' => 'articles#create', as: 'create_article'
  post  '/article/fb/:id' => 'articles#featured_brand', as: 'article_featured_brand'
  delete  '/article/fb/:id/:fb_id' => 'articles#delete_featured_brand', as: 'delete_article_featured_brand'
  post  '/article/fp/:id' => 'articles#featured_product', as: 'article_featured_product'
  delete  '/article/fp/:id/:fp_id' => 'articles#delete_featured_product', as: 'delete_article_featured_product'
  delete  '/article/carousel/:id/' => 'articles#delete_carousel_photo', as: 'delete_article_carousel_photo'
  delete  '/article/tile/:id/' => 'articles#delete_tile_photo', as: 'delete_article_tile_photo'

  resources :article_photos, only: [:create]
  delete '/article_photos/:id/:article_id' => 'article_photos#destroy', as: 'delete_article_photo'

  resources :sectors, only: [:create, :update, :destroy]
  resources :subsectors, only: [:create, :update, :destroy]
  resources :channels, only: [:create, :update, :destroy]
  resources :company_sizes, only: [:create, :update, :destroy]
  resources :key_retailers, only: [:create, :update, :destroy]
  resources :trends, only: [:create, :update, :destroy]
  resources :countries, only: [:create, :update, :destroy]
  resources :channel_capacities, only: [:create, :update, :destroy]
  resources :brand_photos, only: [:create, :destroy]
  resources :contacts, only: [:index, :new, :create, :update, :destroy]
  resources :tags, only: [:new, :create, :destroy]

  post '/bulkupdate' => 'channel_capacities#bulkupdate', as: 'channel_capacity_bulkupdate'

  resources :displays, only: [:create, :update, :destroy]
  put '/displays/:id/:photo' => 'displays#update', as: 'display_delete'
  resources :distributor_brands, only: [:create, :update, :destroy]
  resources :trade_shows, only: [:create, :update, :destroy]
  resources :press_hits, only: [:create, :update, :destroy]
  delete '/press_hits/file_delete/:id' => 'press_hits#file_destroy', as: 'press_hits_file_delete'
  resources :products, only: [:create, :update, :destroy]
  get   'product/preview/:id' => 'products#preview', as: 'product_preview'
  resources :patents, only: [:create, :update, :destroy]
  resources :trademarks, only: [:create, :update, :destroy]
  resources :compliances, only: [:create, :update, :destroy]
  resources :export_countries, only: [:create, :update, :destroy]


  resources :product_photos, only: [:create]
  delete '/product_photos/:id' => 'product_photos#destroy', as: 'product_photo_delete'

  resources :library_documents, only: [:update, :create, :index]
  delete '/library_documents/:id' => 'library_documents#destroy', as: 'library_document_delete'



  # Deprecated
  # resources :sales_sizes, only: [:create, :update, :destroy]
  # resources :marketing_spends, only: [:create, :update, :destroy]
  
  resources :users, only: [:new, :create, :edit, :update, :destroy, :index]
  get    '/users/admin' => 'users#admin_index', as: 'users_admin'
  get    '/user/confirm/:token' => 'users#confirm_email', as: 'user_email_confirmation'
  patch    '/user/lu/:id' => 'users#limited_update', as: 'user_limited_update'

  get    '/distributor/edit' => 'distributors#edit', as: 'distributor'
  get    '/distributor/full_profile' => 'distributors#full_profile', as: 'distributor_full_profile'
  patch  '/distributor/edit' => 'distributors#update'
  patch  '/distributor_brands' => 'distributor_brands#update'
  patch  '/distributor/adminupdate/:id' => 'distributors#adminupdate', as: 'distributor_admin_update'
  delete '/distributor/validation/delitem' => 'distributors#validation_delete', as: 'distributor_validation_delete'

  get    '/retailer/edit' => 'retailers#edit', as: 'retailer'
  get    '/retailer/full_profile' => 'retailers#full_profile', as: 'retailer_full_profile'
  patch  '/retailer/edit' => 'retailers#update'
  patch  '/retailer/adminupdate/:id' => 'retailers#adminupdate', as: 'retailer_admin_update'
  delete '/retailer/validation/delitem' => 'retailers#validation_delete', as: 'retailer_validation_delete'


  # v2 public view
  get    '/brands' => 'brands#index', as: 'brands'
  get    '/brands/s/' => 'brands#search', as: 'search_brands'
  get    '/brand/view/:id' => 'brands#view', as: 'view_brand'
  get    '/brand/preview/:id' => 'brands#preview', as: 'preview_brand'

  get    '/retailer/view/:id' => 'retailers#view', as: 'view_retailer'
  get    '/distributor/view/:id' => 'distributors#view', as: 'view_distributor'

  # for brand editing
  get    '/brand/edit' => 'brands#edit', as: 'brand'
  get    '/brand/full_profile' => 'brands#full_profile', as: 'brand_full_profile'
  patch  '/brand/edit' => 'brands#update'
  patch  '/brand/adminupdate/:id' => 'brands#adminupdate', as: 'brand_admin_update'
  get    '/brand/subscribe' => 'brands#subscription', as: 'brand_subscription'

  # for article brand link
  get    '/brands/list' => 'brands#list', as: 'brand_list'
  # for article product link
  get    '/products/list' => 'products#list', as: 'product_list'

  get '/onboard/distributor/one' => 'onboard_distributor#one', as: 'onboard_distributor_one'
  get '/onboard/distributor/two' => 'onboard_distributor#two', as: 'onboard_distributor_two'
  get '/onboard/distributor/three' => 'onboard_distributor#three', as: 'onboard_distributor_three'
  get '/onboard/distributor/four' => 'onboard_distributor#four', as: 'onboard_distributor_four'
  get '/onboard/distributor/five' => 'onboard_distributor#five', as: 'onboard_distributor_five'
  get '/onboard/distributor/six' => 'onboard_distributor#six', as: 'onboard_distributor_six'
  # get '/onboard/distributor/seven' => 'onboard_distributor#seven', as: 'onboard_distributor_seven'
  # get '/onboard/distributor/eight' => 'onboard_distributor#eight', as: 'onboard_distributor_eight'

  get '/onboard/brand/one' => 'onboard_brand#one', as: 'onboard_brand_one'
  get '/onboard/brand/two' => 'onboard_brand#two', as: 'onboard_brand_two'
  get '/onboard/brand/three' => 'onboard_brand#three', as: 'onboard_brand_three'
  get '/onboard/brand/four' => 'onboard_brand#four', as: 'onboard_brand_four'
  get '/onboard/brand/five' => 'onboard_brand#five', as: 'onboard_brand_five'
  get '/onboard/brand/six' => 'onboard_brand#six', as: 'onboard_brand_six'
  get '/onboard/brand/seven' => 'onboard_brand#seven', as: 'onboard_brand_seven'
  get '/onboard/brand/eight' => 'onboard_brand#eight', as: 'onboard_brand_eight'

  get '/matches' => 'matches#index', as: 'all_matches'
  get '/savedmatches' => 'matches#index_saved_matches', as: 'saved_matches'
  get '/contactedmatches' => 'matches#index_contacted_matches', as: 'contacted_matches'
  get '/incomingmatches' => 'matches#index_incoming_matches', as: 'incoming_matches'
  get '/conversations' => 'matches#index_conversations', as: 'conversations'
  post '/matches' => 'matches#index'
  get '/matches/save/:match_id' => 'matches#save_match', as: 'save_match'
  get '/matches/unsave/:match_id/:remove' => 'matches#unsave_match', as: 'unsave_match'
  get '/matches/view/:match_id/:referrer' => 'matches#view_match', as: 'view_match'
  get '/matches/contact/:match_id' => 'matches#contact_match', as: 'contact_match'
  get '/matches/search' => 'matches#search', as: 'search'
  post '/matches/stage/update/:id' => 'matches#match_stage_update', as: 'match_stage_update'
  get '/matches/stage/view/:id/:stage' => 'matches#match_stage_view', as: 'match_stage_view'
  get '/matches/profilequickview/:match_id' => 'matches#profile_quick_view', as: 'profile_quick_view'
  get '/matches/contract/:match_id' => 'matches#view_contract', as: 'view_contract'
  post '/matches/accept/:id' => 'matches#accept_match', as: 'accept_match'
  get '/gallery' => 'matches#gallery', as: 'gallery'
  get '/gallerynext' => 'matches#gallery_next', as: 'gallery_next'
  # post '/matches/share/:match_id' => 'matches#match_share', as: 'match_share'
  patch '/matches/share/:match_id' => 'matches#match_share', as: 'match_share'

  # post '/conversations/share' => 'conversations#share', as: 'conversation_share'

  resources :messages, only: [:create, :index]
  get '/smsg/:recipient_id' => 'messages#new_simple_message', as: 'new_simple_message'
  post '/smsg/:recipient_id' => 'messages#send_simple_message'
  resources :password_resets
  # get 'messages/all/:match_id' => 'messages#all_messages', as: 'all_messages'

  get '/inventory_adjustments/new/:type/:product_id' => 'inventory_adjustments#new', as: 'new_inventory_adjustment'
  get '/inventory_adjustments/edit/:id' => 'inventory_adjustments#edit', as: 'edit_inventory_adjustment'
  get '/inventory_adjustments/' => 'inventory_adjustments#index', as: 'inventory_adjustments'
  post '/inventory_adjustments/viewtable/' => 'inventory_adjustments#view_table', as: 'view_inventory_table'
  post '/inventory_adjustments/' => 'inventory_adjustments#create'
  put '/inventory_adjustments/:id' => 'inventory_adjustments#update', as: 'inventory_adjustment'
  patch '/inventory_adjustments/:id' => 'inventory_adjustments#update'

app/helpers/profiles_helper.rb
module ProfilesHelper

	def show_links(profile)
		links = []

		unless profile.facebook.blank?
			fb = "<a href='//#{clean_url(profile.facebook)}' target='blank' class='profile-social-link'><img src='https://s3.amazonaws.com/landingintl-us/general/facebook-icon.png' width='30'></a>"
			links << fb
		end 

		unless profile.linkedin.blank?
			li = "<a href='//#{clean_url(profile.linkedin)}' target='blank' class='profile-social-link'><img src='https://s3.amazonaws.com/landingintl-us/general/linkedin-icon.png' width='30'></a>"
			links << li
		end 

		unless profile.twitter.blank?
			twt = "<a href='//#{clean_url(profile.twitter)}' target='blank' class='profile-social-link'><img src='https://s3.amazonaws.com/landingintl-us/general/twitter-icon.png' width='30'></a>"
			links << twt
		end 

		unless profile.instagram.blank?
			ig = "<a href='//#{clean_url(profile.instagram)}' target='blank' class='profile-social-link'><img src='https://s3.amazonaws.com/landingintl-us/general/instagram-icon.png' width='30'></a>"
			links << ig
		end
		unless links.blank?
			return "<div class='profile-general-info-item'><div class='title'>Social:</div>#{links.join(' ')}</div>".html_safe
		end
	end

	def show_global_good_tags(profile)
		tags = ""
		unless profile.tags.blank?
			profile.tags.each do |tag|
				tags += "<span class='profile-tag'>#{tag.name}</span>"
			end
			return "<div class='profile-general-info-item'><div class='title'>Global Good Tags:</div><div class='tagset'>#{tags.html_safe}</div></div>".html_safe
		end
	end

	def show_trend_tags(profile)
		tags = ""
		unless profile.trends.blank?
			profile.trends.pluck(:name).each do |trend|
				tags += "<span class='profile-tag'>#{trend}</span>"
			end
			return "<div class='profile-general-info-item'><div class='title'>Trend Tags:</div><div class='tagset'>#{tags}</div></div>".html_safe
		end
	end

	def show_website_url(profile)
		unless profile.website.blank? 
			link = link_to "#{clean_url(profile.website)}", "//#{clean_url(profile.website)}", target: 'blank', class: 'profile-social-link'
			return "<div class='profile-general-info-item'><div class='title'>Website:</div>#{link}</div>".html_safe
		end

	end

	def show_country_of_origin(profile)
		if profile.country_of_origin.blank?
			item = "n/a"
		else
			item = profile.country_of_origin
		end
		return "<div class='profile-general-info-item'><div class='title'>Country of Origin:</div>#{item}</div>".html_safe
	end

	def show_company_size(profile)
		if profile.company_size.blank?
			item = "n/a"
		else
			item = CompanySize.find(profile.company_size).name rescue nil
		end
		return "<div class='profile-general-info-item'><div class='title'>Company Size:</div>#{item}</div>".html_safe
	end

	def show_order_minimum(profile)
		if profile.order_minimum.blank?
			item = "None"
		else
			item = display_price(profile.order_minimum)
		end
		return "<div class='profile-general-info-item'><div class='title'>Order Minimum:</div>$ #{item}</div>".html_safe
	end

	def show_sectors(profile)
		if profile.sectors.blank? 
			item = "n/a"
		else 
			profile.sectors.order_by(:name => "asc").each do |s| 
				sector = ""
				sector += s.name 
				unless profile.subsectors.where(:sector => s).blank? 
					sector += " (#{profile.subsectors.where(:sector => s).pluck(:name).to_a.join(", ")})"
				end 
				item = sector
			end 
		end
		return "<div class='profile-general-info-item'><div class='title'>Sectors:</div>#{item}</div>".html_safe
	end

	def show_channels(profile)
		unless profile.channels.blank?
			channels = []
			custom_channels = []
			all_channels = ""
			profile.channels.each do |ch| 
				if !profile.channel_capacities.where(channel_id: ch.id).first.capacity.blank?
					capacity = profile.channel_capacities.where(channel_id: ch.id).first.capacity
					channels << "#{ch.name} (#{capacity})"
				else
					channels << "#{ch.name}"
				end
			end 
			if profile.channel_capacities.where(channel_id: 0).length > 0 
				profile.channel_capacities.where(channel_id: 0).each do |cch| 
					custom_channels << "#{cch.custom_channel_name} #{cch.capacity.blank? ? '' : '(' + cch.capacity.to_s + ')'}"
				end
			end
			all_channels += "<div class='profile-general-info-item'><div class='title'>Channels (capacity):</div>#{channels.join('<br>')}</div>"
			all_channels += "<div class='profile-general-info-item'><div class='title'>Custom Channels (capacity):</div>#{custom_channels.join('<br>')}</div>"
			return all_channels.html_safe
		end
	end

	def show_countries_of_distribution(profile) # distributor
		unless profile.export_countries.blank?
			item = profile.export_countries.pluck(:country).join(", ")
			return "<div class='profile-general-info-item'><div class='title'>Countries of Distribution:</div>#{item}</div>".html_safe
		end
	end

	def show_countries_of_operation(profile) # retailer
		unless profile.export_countries.blank?
			item = profile.export_countries.pluck(:country).join(", ")
			return "<div class='profile-general-info-item'><div class='title'>Countries of Operation:</div>#{item}</div>".html_safe
		end
	end

	def show_number_of_locations(profile)
		if profile.number_of_locations.blank?
			item = "n/a"
		else
			item = profile.number_of_locations
		end
		return "<div class='profile-general-info-item'><div class='title'>Number of Locations:</div>#{item}</div>".html_safe
	end

	def show_number_of_brands_sold(profile)
		if profile.number_of_brands_sold.blank?
			item = "n/a"
		else
			item = profile.number_of_brands_sold
		end
		return "<div class='profile-general-info-item'><div class='title'>Number of Brands Sold:</div>#{item}</div>".html_safe
	end

	def profile_status(order)
		case order.status
		when "open"
			if !@current_user.brand
				return "You have an open order"
			else
				return "#{order.orderer.company_name} has an open order"
			end
		when "submitted"
			if !@current_user.brand
				return "You have submitted an order"
			else
				return "#{order.orderer.company_name} has submitted an order"
			end
		when "pending"
			if !@current_user.brand
				return "Order awaiting your approval"
			else
				return "Order awaing approval by #{order.orderer.company_name}"
			end
		when "approved"
			if !@current_user.brand
				return "Order awaiting your transfer of payment to escrow"
			else
				return "Order awaing payment transfer to escrow by #{order.orderer.company_name}"
			end
		when "paid"
			if !@current_user.brand
				return "Order paid and awaiting shipment by #{order.brand.company_name}"
			else
				return "Order paid. Please ship the order to #{order.orderer.company_name}"
			end
		when "shipped"
			if !@current_user.brand
				return "Order has been shipped"
			else
				return "Order has been shipped"
			end
		when "delivered"
			if !@current_user.brand
				return "Order has been delivered and is awaiting your review & payment release"
			else
				return "Order has been delivered and is awaiting review & payment release"
			end
		when "completed"
			if !@current_user.brand
				return "Order has been delivered, payment released and is now complete"
			else
				return "Order has been delivered, payment released and is now complete"
			end
		end
	end


	def show_logo(profile)

		if profile.logo_file_name
			return image_tag profile.logo.url(:medium), alt: "Logo", id: "logo"
		else
			if !profile.facebook.blank? && fb_picture(profile.facebook)
				return image_tag fb_picture(profile.facebook), id: "logo"
			else
				return image_tag profile.logo.url(:medium), width: "100", height: "100", alt: "Logo", id: "logo"
			end
		end

	end

	def get_shipping_terms(profile)
		case profile.us_shipping_terms
		when "Brand"
			return "Brand"
		when "Retailer"
			return "Retailer"
		when nil 
			return nil
		else 
			return "Other"
		end
	end

end

app/views/shared/profile/components/_distributor_marketing_type.html.erb
<span class="productmarketingtype <%= p ? "" : "off" %>"> <%= name %></span>

app/views/shared/profile/components/_gallery.html.erb
<% if gallery && gallery.count > 0 %>
	<div class="gallery-window" >
		<div id="profile_gallery" class="final-tiles-gallery effect-dezoom effect-fade-out caption-top">
			<div class="ftg-items">
				<% gallery.shuffle.each do |item| %>
		    <div class="tile">
					<img class="item" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<%= item.photo.url(:medium) %>" />
					<% if profile.class.to_s.downcase == 'brand' %>
					<span class='title'><%= item.class.to_s == "BrandPhoto" ? item.brand.company_name : item.photographable.name %></span>
					<% else %>
					<span class='title'><%= item.photographable.brand %></span>
					<% end %>
		    </div>
				<% end %>
			</div>
		</div>
	</div>
<% else %>
	<% if profile.class.to_s.downcase == 'distributor' %>
		<div class="gallery-window gallery-distributor">
			&nbsp;
		</div>
	<% else %>
		<div class="gallery-window gallery-brand">
			&nbsp;
		</div>
	<% end %>
<% end %>

app/views/shared/profile/components/_general_info_preview.html.erb
<div class="profile-container">
	<div class="profile-content profile-general-info-preview">

	<div class="hide-for-small-only">
	<ul>
		<li>
			<% if profile.class.to_s == "Brand" %>
			<div class="title">Trends</div>
			<div class="data">
				<% if profile.trends.blank? %>
					n/a
				<% else %>
					<% profile.trends.each do |t| %>
						<%= t.name %><br>
					<% end %>
				<% end %>
			</div>
			<% end %>
		</li>
		<li>
			<div class="title">Country</div>
			<div class="data">
			<% if profile.country_of_origin.blank? %>
				n/a
			<% else %>
			<%= profile.country_of_origin %>
			</div>
			<% end %>
		</li>
		<li>
			<div class="title">Company Size</div>
			<div class="data">
			<% if profile.company_size.blank? %>
				n/a
			<% else %>
				<%= CompanySize.find(profile.company_size).name rescue nil %>
			<% end %>
			</div>
		</li>
		<li>
			<div class="title">Sector</div>
			<div class="data">
			<% if profile.sectors.blank? %>
				n/a
			<% else %>
				
				<% profile.sectors.order_by(:name => "asc").each do |s| %>
					<%= s.name %><br>
					<% unless profile.subsectors.blank? %>
						<% profile.subsectors.order_by(:name => "asc").each do |ss| %>
							<% if ss.sector == s %>
							&nbsp;&nbsp;&ndash; <%= ss.name %><br>
							<% end %>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
			</div>
		</li>
	</ul>
	</div>

	<div class="show-for-small-only">

		<% if profile.class.to_s == "Brand" %>
		<div class="row">
			<div class="small-12 columns">
				<div class="title">Trends</div>
				<div class="data">
				<% if profile.trends.blank? %>
					n/a
				<% else %>
					<% profile.trends.each do |t| %>
						<%= t.name %>
					<% end %>
				<% end %>
				</div>
			</div><!--/.small-12-->
		</div><!--/.row-->
		<% end %>

		<div class="row">
			<div class="small-12 columns">
					<div class="title">Country</div>
					<div class="data">
					<% if profile.country_of_origin.blank? %>
						n/a
					<% else %>
					<%= profile.country_of_origin %>
					<% end %>
					</div>
			</div><!--/.small-12-->
		</div><!--/.row-->


		<div class="row">
			<div class="small-12 columns">
					<div class="title">Company Size</div>
					<div class="data">
					<% if profile.company_size.blank? %>
						n/a
					<% else %>
					<%= CompanySize.find(profile.company_size).name rescue nil %>
					<% end %>
					</div>
			</div><!--/.small-12-->
		</div><!--/.row-->


		<div class="row">
			<div class="small-12 columns">
					<div class="title">Sector</div>
					<div class="data">
					<% if profile.sectors.blank? %>
						n/a
					<% else %>
						<% profile.sectors.order_by(:name => "asc").each do |s| %>
							<%= s.name %><br>
							<% unless profile.subsectors.blank? %>
								<% profile.subsectors.order_by(:name => "asc").each do |ss| %>
									<% if ss.sector == s %>
									&nbsp;&nbsp;&ndash; <%= ss.name %><br>
									<% end %>
								<% end %>
							<% end %>
						<% end %>
					<% end %>
					</div>
			</div><!--/.small-12-->
		</div><!--/.row-->

	</div>


	</div>
	
</div>	

app/views/shared/profile/components/_links.html.erb
<%= show_links(profile) %>

app/views/shared/profile/components/_marketing_type.html.erb
<span class="productmarketingtype <%= p ? "" : "off" %>"> <%= name %></span>

app/views/shared/profile/components/_profile_nav.html.erb
<div id="profile-nav">
	<div id="top">
		<div class="row">		
				<div class="medium-6 columns medium-text-left small-text-center" id="left">
					<h1><%= profile.company_name %></h1>
				</div><!--/.medium-6-->
				<div class="medium-6 columns medium-text-right small-text-center" id="right">
					<%= show_logo(profile) %>
				</div><!--/.medium-6-->			
		</div><!--/.row-->
	</div><!--/.top-->

	<div id="bottom">
		<div class="row">
			<div class="small-12 columns text-left" id="nav">
				<span id="view-orders-buttons"><%= render partial: "shared/profile/components/view_orders_buttons", locals: {profile: profile, section: section} %></span>
			</div><!--/.small-12-->
		</div><!--/.row-->
	</div><!--/.bottom-->
</div><!--/.profile-nav-->

app/views/shared/profile/components/_savebutton.html.erb
<% if @current_user && @current_user.subscriber? %>

	<% if action_name == "index" || action_name == "view_match" || action_name == "contact_match" || action_name == "index_incoming_matches" || action_name == "index_contacted_matches" || action_name == "index_saved_matches" %>
		<% if action_name == "index" || action_name == "view_match" || action_name == "contact_match" || action_name == "index_incoming_matches" || action_name == "index_contacted_matches"%>
			<% if @current_user.send(@current_user.type?).saved_matches.find(profile.id) %>
			<span id="pst_<%= profile.id %>">
				<%= link_to unsave_match_url(profile.id,"false"), remote: true do %>
					<span class="plt-indicator-action-on tiny">Saved</span>
				<% end %>
			</span>
			<% else %>
			<span id="pst_<%= profile.id %>">
				<%= link_to save_match_url(profile.id), remote: true do %>
					<span class="plt-indicator-action-off tiny">Save</span>
				<% end %>
			</span>
			<% end %>
		<% elsif action_name == "index_saved_matches" %>
			<span id="pst_<%= profile.id %>">
				<%= link_to unsave_match_url(profile.id,"true"), remote: true do %>
					<span class="plt-indicator-action-on tiny">Saved</span>
				<% end %>
			</span>
		<% end %>
	<% end %>

<% end %>

app/views/shared/profile/components/_skus.html.erb
<% if profile.products.where(current: true).length > 0 %>

	<div class="small-12 columns">
		<div class="profile-section-head"><%= profile.products.where(current: true).length %> CURRENT SKUs</div>
	</div><!--/.small-12-->
	
	<div class="medium-11 medium-centered columns">
	<% profile.products.where(current: true).order_by(:description.desc, :key_benefits.desc).each do |p| %>
		<%= render partial: "shared/collections_view/products", locals: {
			collitem: p, profile: profile
		} %>
	<% end %>
	</div><!--/.medium-11-->

<% end %>
<% if profile.products.where(current: false).length > 0 %>

	<div class="small-12 columns">
		<div class="profile-section-head"><%= profile.products.where(current: false).length %> FUTURE SKUs</div>
	</div><!--/.small-12-->

	<div class="medium-11 medium-centered columns">
	<% profile.products.where(current: false).order_by(:description.desc, :key_benefits.desc).each do |p| %>												<%= render partial: "shared/collections_view/products", locals: {
			collitem: p, profile: profile
		} %>
	<% end %>
	</div><!--/.medium-11-->

<% end %>

app/views/shared/profile/components/_view_orders_buttons.html.erb
<ul class="navlist" id="left">
	<li <%= section == "profile" ? "class=active" : "" %>>
		<%= link_to eval("view_#{profile.class.to_s.downcase}_url(profile)") do %>
		<div id="profile">PROFILE</div>
		<% end %>
	</li>
	<% if show_orders(profile) %>
		<% if @current_user.company.orders.of_company(company_id: profile.id, type: profile.class.to_s.downcase).count > 0 %>
		<li <%= section == "orders" ? "class=active" : "" %>>
			<%= link_to orders_url(company_id: profile) do %>
				<div id="orders">ORDERS</div>
			<% end %>
		</li>
		<% end %>
	<% end %>
	<% if @current_user.type? != "brand" && order = open_order(profile) %>
	<li <%= section == "cart" ? "class=active" : "" %>>
		<%= link_to order_url(order) do %>
			<div id="shopping-cart">CART <div class="count"><%= order.order_items.count %></div></div>
		<% end %>
	</li>
	<% end %>

</ul>
<ul class="navlist" id="right">
	<li>
		Have questions? <%= link_to "Contact #{profile.company_name}", new_simple_message_url(profile), remote:true %>
	</li>
</ul>