config/routes.rb
  delete '/order/order_items/:o/:id' => 'order_items#destroy', as: 'delete_order_item'

  post   'order/charges/a/:order_id' => 'order_additional_charges#create', as: 'create_order_additional_charge'
  patch   'order/:order_id/charges/u/:id' => 'order_additional_charges#update', as: 'update_order_additional_charge'
  delete   'order/:order_id/charges/d/:id' => 'order_additional_charges#destroy', as: 'delete_order_additional_charge'

  # ARMOR PAYMENTS
  post  '/ap/complete' => 'armor_payments#complete_required', as: 'ap_complete_required'
  post  '/ap/create' => 'armor_payments#create_account', as: 'ap_create_account'
  post  '/ap/disable' => 'armor_payments#disable', as: 'ap_disable'
  post  '/ap/wh' => 'armor_payments#webhook'

  # "static" pages
  get  '/pages/:page' => 'pages#show'

  resources :articles, only: [:index, :show, :update, :destroy]
  get  '/article/view/:id' => 'articles#public_view', as: 'public_view_article'
  post  '/article/new/:type' => 'articles#create', as: 'create_article'
  post  '/article/fb/:id' => 'articles#featured_brand', as: 'article_featured_brand'
  delete  '/article/fb/:id/:fb_id' => 'articles#delete_featured_brand', as: 'delete_article_featured_brand'
  post  '/article/fp/:id' => 'articles#featured_product', as: 'article_featured_product'
  delete  '/article/fp/:id/:fp_id' => 'articles#delete_featured_product', as: 'delete_article_featured_product'
  delete  '/article/carousel/:id/' => 'articles#delete_carousel_photo', as: 'delete_article_carousel_photo'
  delete  '/article/tile/:id/' => 'articles#delete_tile_photo', as: 'delete_article_tile_photo'

  resources :article_photos, only: [:create]
  delete '/article_photos/:id/:article_id' => 'article_photos#destroy', as: 'delete_article_photo'

  resources :sectors, only: [:create, :update, :destroy]
  resources :subsectors, only: [:create, :update, :destroy]
  resources :channels, only: [:create, :update, :destroy]
  resources :company_sizes, only: [:create, :update, :destroy]
  resources :key_retailers, only: [:create, :update, :destroy]
  resources :trends, only: [:create, :update, :destroy]
  resources :countries, only: [:create, :update, :destroy]
  resources :channel_capacities, only: [:create, :update, :destroy]
  resources :brand_photos, only: [:create, :destroy]
  resources :contacts, only: [:index, :new, :create, :update, :destroy]
  resources :tags, only: [:new, :create, :destroy]

  post '/bulkupdate' => 'channel_capacities#bulkupdate', as: 'channel_capacity_bulkupdate'

  resources :displays, only: [:create, :update, :destroy]
  put '/displays/:id/:photo' => 'displays#update', as: 'display_delete'
  resources :distributor_brands, only: [:create, :update, :destroy]
  resources :trade_shows, only: [:create, :update, :destroy]
  resources :press_hits, only: [:create, :update, :destroy]
  delete '/press_hits/file_delete/:id' => 'press_hits#file_destroy', as: 'press_hits_file_delete'
  resources :products, only: [:create, :update, :destroy]
  get   'product/preview/:id' => 'products#preview', as: 'product_preview'
  resources :patents, only: [:create, :update, :destroy]
  resources :trademarks, only: [:create, :update, :destroy]
  resources :compliances, only: [:create, :update, :destroy]
  resources :export_countries, only: [:create, :update, :destroy]


  resources :product_photos, only: [:create]
  delete '/product_photos/:id' => 'product_photos#destroy', as: 'product_photo_delete'

  resources :library_documents, only: [:update, :create, :index]
  delete '/library_documents/:id' => 'library_documents#destroy', as: 'library_document_delete'



  # Deprecated
  # resources :sales_sizes, only: [:create, :update, :destroy]
  # resources :marketing_spends, only: [:create, :update, :destroy]
  
  resources :users, only: [:new, :create, :edit, :update, :destroy, :index]
  get    '/users/admin' => 'users#admin_index', as: 'users_admin'
  get    '/user/confirm/:token' => 'users#confirm_email', as: 'user_email_confirmation'
  patch    '/user/lu/:id' => 'users#limited_update', as: 'user_limited_update'

  get    '/distributor/edit' => 'distributors#edit', as: 'distributor'
  get    '/distributor/full_profile' => 'distributors#full_profile', as: 'distributor_full_profile'
  patch  '/distributor/edit' => 'distributors#update'
  patch  '/distributor_brands' => 'distributor_brands#update'
  patch  '/distributor/adminupdate/:id' => 'distributors#adminupdate', as: 'distributor_admin_update'
  delete '/distributor/validation/delitem' => 'distributors#validation_delete', as: 'distributor_validation_delete'

  get    '/retailer/edit' => 'retailers#edit', as: 'retailer'
  get    '/retailer/full_profile' => 'retailers#full_profile', as: 'retailer_full_profile'
  patch  '/retailer/edit' => 'retailers#update'
  patch  '/retailer/adminupdate/:id' => 'retailers#adminupdate', as: 'retailer_admin_update'
  delete '/retailer/validation/delitem' => 'retailers#validation_delete', as: 'retailer_validation_delete'


  # v2 public view
  get    '/brands' => 'brands#index', as: 'brands'
  get    '/brands/s/' => 'brands#search', as: 'search_brands'
  get    '/brand/view/:id' => 'brands#view', as: 'view_brand'
  get    '/brand/preview/:id' => 'brands#preview', as: 'preview_brand'

  get    '/retailer/view/:id' => 'retailers#view', as: 'view_retailer'
  get    '/distributor/view/:id' => 'distributors#view', as: 'view_distributor'

  # for brand editing
  get    '/brand/edit' => 'brands#edit', as: 'brand'
  get    '/brand/full_profile' => 'brands#full_profile', as: 'brand_full_profile'
  patch  '/brand/edit' => 'brands#update'
  patch  '/brand/adminupdate/:id' => 'brands#adminupdate', as: 'brand_admin_update'
  get    '/brand/subscribe' => 'brands#subscription', as: 'brand_subscription'

  # for article brand link
  get    '/brands/list' => 'brands#list', as: 'brand_list'
  # for article product link
  get    '/products/list' => 'products#list', as: 'product_list'

  get '/onboard/distributor/one' => 'onboard_distributor#one', as: 'onboard_distributor_one'
  get '/onboard/distributor/two' => 'onboard_distributor#two', as: 'onboard_distributor_two'
  get '/onboard/distributor/three' => 'onboard_distributor#three', as: 'onboard_distributor_three'
  get '/onboard/distributor/four' => 'onboard_distributor#four', as: 'onboard_distributor_four'
  get '/onboard/distributor/five' => 'onboard_distributor#five', as: 'onboard_distributor_five'
  get '/onboard/distributor/six' => 'onboard_distributor#six', as: 'onboard_distributor_six'
  # get '/onboard/distributor/seven' => 'onboard_distributor#seven', as: 'onboard_distributor_seven'
  # get '/onboard/distributor/eight' => 'onboard_distributor#eight', as: 'onboard_distributor_eight'

  get '/onboard/brand/one' => 'onboard_brand#one', as: 'onboard_brand_one'
  get '/onboard/brand/two' => 'onboard_brand#two', as: 'onboard_brand_two'
  get '/onboard/brand/three' => 'onboard_brand#three', as: 'onboard_brand_three'
  get '/onboard/brand/four' => 'onboard_brand#four', as: 'onboard_brand_four'
  get '/onboard/brand/five' => 'onboard_brand#five', as: 'onboard_brand_five'
  get '/onboard/brand/six' => 'onboard_brand#six', as: 'onboard_brand_six'
  get '/onboard/brand/seven' => 'onboard_brand#seven', as: 'onboard_brand_seven'
  get '/onboard/brand/eight' => 'onboard_brand#eight', as: 'onboard_brand_eight'

  get '/matches' => 'matches#index', as: 'all_matches'
  get '/savedmatches' => 'matches#index_saved_matches', as: 'saved_matches'
  get '/contactedmatches' => 'matches#index_contacted_matches', as: 'contacted_matches'
  get '/incomingmatches' => 'matches#index_incoming_matches', as: 'incoming_matches'
  get '/conversations' => 'matches#index_conversations', as: 'conversations'
  post '/matches' => 'matches#index'
  get '/matches/save/:match_id' => 'matches#save_match', as: 'save_match'
  get '/matches/unsave/:match_id/:remove' => 'matches#unsave_match', as: 'unsave_match'
  get '/matches/view/:match_id/:referrer' => 'matches#view_match', as: 'view_match'
  get '/matches/contact/:match_id' => 'matches#contact_match', as: 'contact_match'
  get '/matches/search' => 'matches#search', as: 'search'
  post '/matches/stage/update/:id' => 'matches#match_stage_update', as: 'match_stage_update'
  get '/matches/stage/view/:id/:stage' => 'matches#match_stage_view', as: 'match_stage_view'
  get '/matches/profilequickview/:match_id' => 'matches#profile_quick_view', as: 'profile_quick_view'
  get '/matches/contract/:match_id' => 'matches#view_contract', as: 'view_contract'
  post '/matches/accept/:id' => 'matches#accept_match', as: 'accept_match'
  get '/gallery' => 'matches#gallery', as: 'gallery'
  get '/gallerynext' => 'matches#gallery_next', as: 'gallery_next'
  # post '/matches/share/:match_id' => 'matches#match_share', as: 'match_share'
  patch '/matches/share/:match_id' => 'matches#match_share', as: 'match_share'

  # post '/conversations/share' => 'conversations#share', as: 'conversation_share'

  resources :messages, only: [:create, :index]
  get '/smsg/:recipient_id' => 'messages#new_simple_message', as: 'new_simple_message'
  post '/smsg/:recipient_id' => 'messages#send_simple_message'
  resources :password_resets
  # get 'messages/all/:match_id' => 'messages#all_messages', as: 'all_messages'

  get '/inventory_adjustments/new/:type/:product_id' => 'inventory_adjustments#new', as: 'new_inventory_adjustment'
  get '/inventory_adjustments/edit/:id' => 'inventory_adjustments#edit', as: 'edit_inventory_adjustment'
  get '/inventory_adjustments/' => 'inventory_adjustments#index', as: 'inventory_adjustments'
  post '/inventory_adjustments/viewtable/' => 'inventory_adjustments#view_table', as: 'view_inventory_table'
  post '/inventory_adjustments/' => 'inventory_adjustments#create'
  put '/inventory_adjustments/:id' => 'inventory_adjustments#update', as: 'inventory_adjustment'
  patch '/inventory_adjustments/:id' => 'inventory_adjustments#update'

app/models/match.rb
class Match
  include Mongoid::Document
	include Mongoid::Timestamps::Short

	belongs_to :distributor
	belongs_to :brand

  # to identify who initiated
  belongs_to :user

  field :initial_contact_by, type: String

  # is the match accepted by contactee
  field :accepted, type: Mongoid::Boolean
  field :intro_message, type: String
  field :stage, type: String, default: "contact"  # stage: [contact,propose,prepare,order]

  field :brand_proceed_to_next_stage, type: Mongoid::Boolean
  field :distributor_proceed_to_next_stage, type: Mongoid::Boolean

  field :brand_shared_propose, type: Mongoid::Boolean
  field :distributor_shared_propose, type: Mongoid::Boolean
  field :brand_shared_prepare, type: Mongoid::Boolean
  field :distributor_shared_prepare, type: Mongoid::Boolean

  # CONTRACT FIELDS
  # BRAND
  # documents
  field :tiered_pricing_schedule, type: Array, default: []
  field :fob_pricing, type: Array, default: []
  field :products_list, type: Array, default: []
  field :certification_information_documents, type: Array, default: []
  field :patent_information_documents, type: Array, default: []
  field :testing_information_documents, type: Array, default: []
  field :ingredient_or_materials_lists, type: Array, default: []

  # text fields
  field :partnership_start_date, type: Date
  field :partnership_terms_length, type: String, default: "3 years"
  field :renewal_terms, type: String, default: ""
  field :termination_terms, type: String, default: ""
  field :payment_terms, type: String, default: ""
  field :territory_exclusivity_terms, type: String, default: ""
  field :requested_minimum_marketing_spend, type: String, default: ""
  field :marketing_requests_or_requirements, type: String, default: ""
  field :retail_channel_requests_or_requirements, type: String, default: ""
  field :order_turnaround, type: String, default: ""
  field :pricing_amendments, type: String, default: ""

  # DISTRIBUTOR
  # text fields
  field :brand_launch_plan, type: String, default: ""
  field :marketing_strategy, type: String, default: ""
  field :minimum_volume_year_one, type: String, default: ""
  field :minimum_volume_year_two, type: String, default: ""
  field :minimum_volume_year_three, type: String, default: ""
  field :testing_information, type: String, default: ""
  field :certification_information, type: String, default: ""
  field :customs_information, type: String, default: ""
  field :labeling_information, type: String, default: ""
  field :tariffs_information, type: String, default: ""
  field :contract_authentication, type: String, default: ""
  field :shipping, type: String, default: ""
  field :channel_rights, type: String, default: ""
  field :marketing_commitments, type: String, default: ""

  field :account_executive, type: String, default: ""
  field :warehouse_contact, type: String, default: ""
  field :freight_forwarder, type: String, default: ""

  #checkboxes
  field :territory, type: Array, default: []
  field :initial_channels, type: Array, default: []
  field :second_tier_channels, type: Array, default: []
  field :third_tier_channels, type: Array, default: []
  field :marketing_channels, type: Array, default: []
  field :skus_for_testing, type: Hash, default: {}

  has_many :messages, dependent: :destroy

  def get_b_or_d(current_user)
    return self.send(current_user.type_inverse?)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper


	def get_conversation_stage(match)
		# stage = match.stage
		# stage ||= 'contact'
		return match.stage
	end

	def get_match(profile)
		b_or_d = @current_user.send(@current_user.type?)
		if @current_user.type? == 'brand'
			if this_match = @current_user.send(@current_user.type?).matches.where(distributor_id: profile.id).first
				return this_match
			else
				return false
			end
		elsif @current_user.type? == 'distributor'
			if this_match = @current_user.send(@current_user.type?).matches.where(brand_id: profile.id).first
				return this_match
			else
				return false
			end
		end
	end


	def get_photos(profile)
		b_photos = Array.new
		profile.brand_photos.each do |item|
			b_photos << item
		end

		p_photos = Array.new
		profile.products.each do |product|
			product.product_photos.each do |photo|
				p_photos << photo
			end
		end

		photos = Array.new
		photos = b_photos.shuffle[0..7] + p_photos.shuffle[0..7]
		return photos.shuffle
	end


	def get_last_login(match)

		login_list = Array.new
		match.users.each do |user|
			if user.last_login
				login_list << user.last_login
			end
		end
		return login_list.sort!.last

	end

end

app/views/matches/_brand_match_list.html.erb
<% ort ||= "sq" %>
<% set ||= nil %>
<% if @current_user.subscriber? %>

	<% if matches.blank? %>

		<%= render "no_matches" %>

	<% else %>
		
		<% case ort %>
		<% when "hz" %>
			<div class="row" style="padding: 0px;">
				<div class="small-12 columns">
					<% matches.each do |match| %>
						<%= render partial: "shared/profile/profile_list_tile_small_h", locals: {profile_item: match, set: set} %>
					<% end %>
				</div>
			</div>
		<% when "sq" %>
			<div class="row" style="padding: 0px;">
				<div class="small-12 columns">
					<ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-2 ">
						<% matches.each do |match| %>
						<li><%= render partial: "shared/profile/profile_list_tile_small_sq", locals: {profile_item: match, set: set} %></li>
						<% end %>
					</ul>
				</div>
			</div>
		<% end %>

	<% end %>

<% else %>

	<% if action_name == "index" %>

		<% if matches.blank? %>
			<div class="row">
				<div class="small-10 small-centered columns previewtile text-center">
						<h2>No Distributors</h2>
				</div>
			</div>
		<% else %>


			<div class="row" style="padding: 0px;">
				<div class="small-12 columns">
					<% matches.each do |match| %>
						<%= render partial: "shared/profile/profile_list_tile_small_h", locals: {profile_item: match, set: set} %>
					<% end %>
				</div>
			</div>


		<% end %>

	<% else %>

		<div class="row">
			<div class="small-10 small-centered columns previewtile text-center">
				<h1>Available to subscribers only</h1>
				<% if @new_contact_messages > 0 %>
					<h3>You have been contacted by <%= @new_contact_messages %> <%= @current_user.type_inverse? %><%= @new_contact_messages > 1 ? "s" : "" %><br>
						<%= link_to 'SUBSCRIBE', '#' %> to connect!
					</h3>
				<% end %>				
			</div>
		</div>

	<% end %>

<% end %>

app/views/matches/_distributor_filter_form.html.erb
<div id="filter-form-container" <%= action_name != "index" ? "style='display: none;'".html_safe : "" %> >
	<div class="clearfix">
	<ul class="tabs right" data-tab role="tablist">
	  <li class="tab-title active" role="presentational" ><a href="#panel2-1" role="tab" tabindex="0" aria-selected="true" controls="panel2-1">Brand Match</a></li>
	  <li class="tab-title" role="presentational" ><a href="#panel2-2" role="tab" tabindex="0"aria-selected="false" controls="panel2-2">Search by Name</a></li>
	</ul>
	</div>

	<div class="tabs-content">
		<section role="tabpanel" aria-hidden="false" class="content active" id="panel2-1">
			<div class="filter-form-panel">
				<h2><strong> I'm Looking for Brands... </strong></h2>
				<%= form_tag all_matches_url, id: 'filters-form', method: 'post', remote: true do %>
				<%= hidden_field_tag "filter_form", "true" %>
				<div class="row filterform">
					<div class="small-12 columns">
						<strong><small>From:</small></strong>					
						<% @countries.each_with_index do |co, index| %>
							<%= render partial: "shared/filter_checkbox", locals: {field: "country", label: co, fid: co, cbid: "country_#{index}", on_off_switch: filter_on_or_off(co, @country), cclass: "mfcountry" } %>
						<% end %>
						<input id="selectallcountries" name="selectallcountries" type="checkbox" style="font-color: black;" class="filter" checked/>
						<label for="selectallcountries" style="color: black; border: 1px dotted black; background: transparent;">Select/Deselect All</label>
					<br><br>
					</div>
				</div>
				<div class="row filterform">
					<div class="small-12 columns">
						<strong><small>in these Sectors:</small></strong>
						<% @profile.sectors.each_with_index do |co, index| %>
							<%= render partial: "shared/filter_checkbox", locals: {field: "sector", label: co.name, fid: co.id, cbid: "sector_#{index}", on_off_switch: filter_on_or_off(co.id.to_s, @sector), cclass: "mfsector" } %>
						<% end %>
						<input id="selectallsectors" name="selectallsectors" type="checkbox" style="font-color: black;" class="filter" checked/>
						<label for="selectallsectors" style="color: black; border: 1px dotted black; background: transparent;">Select/Deselect All</label>
					<br><br>
					</div>
				</div>
				<div class="row filterform">
					<div class="small-12 columns">
						<strong><small>That Sell In:</small></strong>
						<% @profile.channels.each_with_index do |co, index| %>
							<%= render partial: "shared/filter_checkbox", locals: {field: "channel", label: co.name, fid: co.id, cbid: "channel_#{index}", on_off_switch: filter_on_or_off(co.id.to_s, @channel), cclass: "mfchannel" } %>
						<% end %>
						<input id="selectallchannels" name="selectallchannels" type="checkbox" style="font-color: black;" class="filter" checked/>
						<label for="selectallchannels" style="color: black; border: 1px dotted black; background: transparent;">Select/Deselect All</label>
					</div>
				</div>
				<% end %>
			</div>
		</section>
		<section role="tabpanel" aria-hidden="false" class="content" id="panel2-2">
		<div class="row">
			<div class="small-12 columns">
				<%= form_tag(search_url, method: "get", remote: true) do %>
					<div class="row">
					  
					  <div class="small-11 small-centered columns">
					  	<%= label_tag(:q, "Search for:") %>
						  <%= text_field_tag :q, "", :placeholder => 'Search For' %>	
					  </div><!--/.small-11 small-centered -->
					  <div class="small-11 small-centered columns">
						  <%= submit_tag "Search", class: 'button alert tiny right' %>	
					  </div><!--/.small-11 small-centered -->
					</div>
				<% end %>
			</div><!--/.small-12-->
		</div>
		</section>	
	</div>



</div> <!-- #filter-form-container -->

app/views/matches/_gallery_results.html.erb
<% @gallery.each do |gallerybrand| %>
	<% product = gallerybrand %>
	<li>
		<div class="gallery-item">
		<div class="row">
			<div class="small-12 columns text-center">
				<%= link_to view_match_path(product.photographable.brand.id, "na") do %>
				<%= image_tag product.photo.url(:profile_tile) %>
				<% end %>
			</div><!--/.medium-5-->
		</div><!--/.row-->
		<div class="row collapse">
			<div class="small-12 columns text-center">
				<%= link_to view_match_path(gallerybrand.id, "na") do %>
				<h3><%= product.photographable.brand.company_name %><br><small><%= product.photographable.name %></small></h3>
				<% end %>
			</div>
		</div><!--/.row-->
		</div>
	</li>
<% end %>

app/views/matches/_save_link.html.erb
<%= link_to save_match_url(@mid), remote: true do %>
	<span class="plt-indicator-action-off tiny">Save</span>
<% end %>

app/views/matches/_unsave_link.html.erb
<%= link_to unsave_match_url(@mid,"false"), remote: true do %>
	<span class="plt-indicator-action-on tiny">Saved</span>
<% end %>

app/views/matches/index.html.erb
<%= render partial: "shared/topbar"%>

<%= render partial: "shared/marketplace_subhead", locals: {section: "FIND #{@current_user.type_inverse?.capitalize}S"} %>

<div class="row collapse">
	<div class="small-12 columns">


<% if @current_user.send(@current_user.type?).sectors.blank? %>
	<div class="row">
		<div class="medium-8 medium-centered columns">
			<div class="panel text-left">
				<div class="row">
					<div class="medium-2 columns">
						<h1>[ <strong style="color: red;">!</strong> ]</h1>
					</div><!--/.medium-4-->
					<div class="medium-10 columns">
						<h3>You don't have you SECTOR designated in 
							<%= link_to 'Your Profile', eval("#{@current_user.type?}_url(:anchor => 'a-sectors')") %>
						</h3>
						<h3>You can't get matched with <%=@current_user.type_inverse?.capitalize%>s without a designated SECTOR.</h3>			
					</div><!--/.medium-10-->
				</div><!--/.row-->
			</div>
		</div><!--/.medium-6 medium-centered-->
	</div><!--/.row-->
<% else %>

	<% case @current_user.type? %>
	<% when 'brand'%>

		<div class="row" data-equalizer>
			<div style="background: white;">
			<div class="medium-3 columns" style="background: white;" data-equalizer-watch><h1>FIND DISTRIBUTORS IN NEW MARKETS</h1>		</div><!--/.medium-3-->
			<div class="medium-6 columns" style="background: white;" data-equalizer-watch>
				<div id="match-map-container">

					<div id="match-search">
						<%= render partial: "brand_search_start" %>
					</div>

				</div><!--/.match-map-container -->
			</div><!--/.medium-6-->
			<div class="medium-3 columns" style="background: white;" data-equalizer-watch> &nbsp; </div><!--/.medium-3-->
			</div>
		</div>

	<% if @country %>	

	<div class="marketplace-content padded">
		<h1><%= @country_proper.upcase %></h1>
		<%= render "tag_filter_label" %>
		<strong><%= render partial: "counts", locals: {matches: @matches} %></strong>
				<div class="row">
					<div class="small-6 columns">
						<%= paginate @matches %>
					</div><!--/.small-6-->
					<div class="small-6 columns text-right">
						<%= render "list_style" %>		
					</div><!--/.small-6-->
				</div><!--/.row-->
		<hr>
		<div id="match-list">
			<div class="row">
				<div class="small-12 columns" >
					<%= render partial: 'brand_match_list', locals: {matches: @matches, ort: @list_style} %>
				</div>
			</div>
		</div>
		<%= paginate @matches %>
	</div>

	<% else %>

	<div class="marketplace-content padded">
		<h1>ALL COUNTRIES</h1>
		<%= render "tag_filter_label" %>
		<strong><%= render partial: "counts", locals: {matches: @matches} %></strong>
				<div class="row">
					<div class="small-6 columns">
						<%= paginate @matches %>		
					</div><!--/.small-6-->
					<div class="small-6 columns text-right">
						<%= render "list_style" %>		
					</div><!--/.small-6-->
				</div><!--/.row-->
		<hr>
		<div id="match-list">
			<div class="row">
				<div class="small-12 columns" >
					<%= render partial: 'brand_match_list', locals: {matches: @matches, ort: @list_style} %>
				</div>
			</div>
		</div>
		<%= paginate @matches %>
	</div>

	<% end %>

	<% when 'distributor' %>

		<div class="row" data-equalizer>
			<div class="medium-3 columns" style="background: white;" data-equalizer-watch><h1>FIND NEW BRANDS</h1>		</div><!--/.medium-3-->
			<div class="medium-8 columns" style="background: white;" data-equalizer-watch>

				<br>
				<%#	<%= form_tag(search_path, method: "get", remote: true) do |f| %>
				<%#	<div class="row collapse">
				<%#	<div class="small-10 columns">
				<%#		<%= text_field_tag :q, '', label: false, placeholder: "SEARCH BY NAME" %>	
				<%#	</div><!--/.small-10-->
				<%#	<div class="small-2 columns">
				<%#		<%= submit_tag 'SEARCH', class: "button postfix tiny alert" %>
				<%#	</div><!--/.small-2-->
				<%#	</div><!--/.row-->
				<%#	<% end %>
						

				<div id="match-sectors-container">
					<div id="match-search">
						<%= render partial: "distributor_search_start" %>
					</div>
				</div><!--/.match-map-container -->
			</div><!--/.medium-6-->
			<div class="medium-1 columns" style="background: white;" data-equalizer-watch> &nbsp; </div><!--/.medium-3-->
		</div>

		<% if @sector %>	
			<div class="marketplace-content padded">
				<h1><%= Sector.find(@sector).name %></h1>
				<%= render "tag_filter_label" %>
				<strong><%= render partial: "counts", locals: {matches: @matches} %></strong>
				<div class="row">
					<div class="small-6 columns">
						<%= paginate @matches %>		
					</div><!--/.small-6-->
					<div class="small-6 columns text-right">
						<%= render "list_style" %>		
					</div><!--/.small-6-->
				</div><!--/.row-->
				<hr>
				<div id="match-list">
					<div class="row">
						<div class="small-12 columns" >
							<%= render partial: 'distributor_match_list', locals: {matches: @matches, ort: @list_style}  %>
						</div>
					</div>
				</div>
				<%= paginate @matches %>
			</div>
		<% else %>

			<div class="marketplace-content padded">
				<h1>ALL SECTORS</h1>
				<%= render "tag_filter_label" %>
				<strong><%= render partial: "counts", locals: {matches: @matches} %></strong>
				<div class="row">
					<div class="small-6 columns">
						<%= paginate @matches %>		
					</div><!--/.small-6-->
					<div class="small-6 columns text-right">
						<%= render "list_style" %>		
					</div><!--/.small-6-->
				</div><!--/.row-->
				<hr>
				<div id="match-list">
					<div class="row">
						<div class="small-12 columns" >
							<%= render partial: 'distributor_match_list', locals: {matches: @matches, ort: @list_style} %>
						</div>
					</div>
				</div>
				<%= paginate @matches %>
			</div>

		<% end %>

	<% end %>


<% end %>

	</div><!--/.small-12 medium-10 -->
</div><!--/.row-->

app/views/matches/save_match.js.erb
$('#pst_<%= @mid %>').html("<%= j (render 'unsave_link') %>");