config/routes.rb
Rails.application.routes.draw do

  root 'home#front'


  get   '/login' => 'session#new', as: 'login'
  post  '/login' => 'session#create'
  get   '/logout' => 'session#destroy', as: 'logout'

  get   '/ps/:id/' => 'home#prospect_share', as: 'prospect_share'
  post   '/ps/l' => 'home#prospect_share_login', as: 'prospect_share_login'

  get   '/dashboard' => 'home#dashboard', as: 'dashboard'

  get   '/admin' => 'admin#index', as: 'admin'
  get   '/admin/new_bulk_upload' => 'admin#new_bulk_upload', as: 'new_bulk_upload'
  post   '/admin/new_bulk_upload' => 'admin#do_bulk_upload'
  get   '/admin/distributors' => 'admin#distributors_index', as: 'admin_distributors_index'
  get   '/admin/brands' => 'admin#brands_index', as: 'admin_brands_index'
  get   '/admin/retailers' => 'admin#retailers_index', as: 'admin_retailers_index'
  get   '/admin/orders/:group' => 'admin#orders_index', as: 'admin_orders_index'
  post   '/admin/orders/search/' => 'admin#orders_search', as: 'admin_orders_search'
  post   '/admin/orders/bc/' => 'admin#orders_by_company', as: 'admin_view_orders_by_company'
  get   '/admin/orders/search/pre/brands' => 'admin#orders_pre_search_brands', as: 'admin_orders_pre_search_brands'
  get   '/admin/orders/search/pre/buyers' => 'admin#orders_pre_search_buyers', as: 'admin_orders_pre_search_buyers'
  get   '/admin/order/d/:id/:confirm' => 'admin#order_destroy', as: 'admin_order_destroy'
  get   '/admin/distributor/:id' => 'admin#distributor_view', as: 'admin_distributor_view'
  get   '/admin/brand/:id' => 'admin#brand_view', as: 'admin_brand_view'
  get   '/admin/retailer/:id' => 'admin#retailer_view', as: 'admin_retailer_view'
  get   '/admin/order/:id' => 'admin#order_view', as: 'admin_order_view'
  post   '/admin/adduser/:id' => 'admin#add_user', as: 'admin_add_user'
  delete   '/admin/deleteuser/:id' => 'admin#delete_user', as: 'admin_delete_user'


  # ORDERS
  resources :orders, only: [:show, :edit, :update, :destroy, :index]
  post   '/orders/search/' => 'orders#orders_search', as: 'orders_search'
  post   '/order/new' => 'orders#create', as: 'new_order'
  get   '/order/s/:id/:confirm' => 'orders#submit', as: 'submit_order'
  get   '/order/p/:id/:confirm' => 'orders#pending', as: 'pending_order'
  patch   '/order/p/:id/:confirm' => 'orders#pending'
  get   '/order/a/:id/:confirm' => 'orders#approve', as: 'approve_order'
  get   '/order/da/:id/:confirm' => 'orders#decline_approval', as: 'decline_approval_order'
  patch '/order/da/:id/:confirm' => 'orders#decline_approval'
  post  '/order/shipment/:id' => 'orders#shipment', as: 'order_shipment_info'
  # for non armor orders
  get   '/order/c/:id/:confirm' => 'orders#complete', as: 'complete_order'
  get   '/order/add/:id/:confirm' => 'orders#armor_disabled_delivered', as: 'armor_disabled_received_order'
  get   '/order/adc/:id/:confirm' => 'orders#armor_disabled_completed', as: 'armor_disabled_completed_order'
  # for order comments
  patch   '/order/comments/:id' => 'comments#update', as: 'order_update_comment'
  # order-calculator display
  get   'order/calculator/show/:id' => 'orders#show_calculator', as: 'show_order_calculator'

# PACKING LISTS

  get   '/admin/packinglists' => 'packing_lists#index', as: 'packing_lists'
  get   '/admin/packinglist/new' => 'packing_lists#new', as: 'new_packing_list'
  patch   '/admin/packinglist/update' => 'packing_lists#update', as: 'update_packing_list'

# comments
  resources :comments, only: [:create]

  # ARMOR PAYMENTS TESTING
  get   '/order/paid/:id/:confirm' => 'orders#paid', as: 'paid_order'
  get   '/order/delivered/:id/:confirm' => 'orders#delivered', as: 'delivered_order'

  resources :order_items, only: [:create, :edit, :update, :index]
  get   '/order/newitem/:product_id' => 'order_items#new', as: 'new_order_item'
  delete '/order/order_items/:o/:id' => 'order_items#destroy', as: 'delete_order_item'

  post   'order/charges/a/:order_id' => 'order_additional_charges#create', as: 'create_order_additional_charge'
  patch   'order/:order_id/charges/u/:id' => 'order_additional_charges#update', as: 'update_order_additional_charge'
  delete   'order/:order_id/charges/d/:id' => 'order_additional_charges#destroy', as: 'delete_order_additional_charge'

  # ARMOR PAYMENTS
  post  '/ap/complete' => 'armor_payments#complete_required', as: 'ap_complete_required'
  post  '/ap/create' => 'armor_payments#create_account', as: 'ap_create_account'
  post  '/ap/disable' => 'armor_payments#disable', as: 'ap_disable'
  post  '/ap/wh' => 'armor_payments#webhook'

  # "static" pages
  get  '/pages/:page' => 'pages#show'

  resources :articles, only: [:index, :show, :update, :destroy]
  get  '/article/view/:id' => 'articles#public_view', as: 'public_view_article'
  post  '/article/new/:type' => 'articles#create', as: 'create_article'
  post  '/article/fb/:id' => 'articles#featured_brand', as: 'article_featured_brand'
  delete  '/article/fb/:id/:fb_id' => 'articles#delete_featured_brand', as: 'delete_article_featured_brand'
  post  '/article/fp/:id' => 'articles#featured_product', as: 'article_featured_product'
  delete  '/article/fp/:id/:fp_id' => 'articles#delete_featured_product', as: 'delete_article_featured_product'
  delete  '/article/carousel/:id/' => 'articles#delete_carousel_photo', as: 'delete_article_carousel_photo'
  delete  '/article/tile/:id/' => 'articles#delete_tile_photo', as: 'delete_article_tile_photo'

  resources :article_photos, only: [:create]
  delete '/article_photos/:id/:article_id' => 'article_photos#destroy', as: 'delete_article_photo'

  resources :sectors, only: [:create, :update, :destroy]
  resources :subsectors, only: [:create, :update, :destroy]
  resources :channels, only: [:create, :update, :destroy]
  resources :company_sizes, only: [:create, :update, :destroy]
  resources :key_retailers, only: [:create, :update, :destroy]
  resources :trends, only: [:create, :update, :destroy]
  resources :countries, only: [:create, :update, :destroy]
  resources :channel_capacities, only: [:create, :update, :destroy]
  resources :brand_photos, only: [:create, :destroy]
  resources :contacts, only: [:index, :new, :create, :update, :destroy]
  resources :tags, only: [:new, :create, :destroy]

  post '/bulkupdate' => 'channel_capacities#bulkupdate', as: 'channel_capacity_bulkupdate'

  resources :displays, only: [:create, :update, :destroy]
  put '/displays/:id/:photo' => 'displays#update', as: 'display_delete'
  resources :distributor_brands, only: [:create, :update, :destroy]
  resources :trade_shows, only: [:create, :update, :destroy]
  resources :press_hits, only: [:create, :update, :destroy]
  delete '/press_hits/file_delete/:id' => 'press_hits#file_destroy', as: 'press_hits_file_delete'
  resources :products, only: [:create, :update, :destroy]
  get   'product/preview/:id' => 'products#preview', as: 'product_preview'
  resources :patents, only: [:create, :update, :destroy]
  resources :trademarks, only: [:create, :update, :destroy]
  resources :compliances, only: [:create, :update, :destroy]
  resources :export_countries, only: [:create, :update, :destroy]


  resources :product_photos, only: [:create]
  delete '/product_photos/:id' => 'product_photos#destroy', as: 'product_photo_delete'

  resources :library_documents, only: [:update, :create, :index]
  delete '/library_documents/:id' => 'library_documents#destroy', as: 'library_document_delete'



  # Deprecated
  # resources :sales_sizes, only: [:create, :update, :destroy]
  # resources :marketing_spends, only: [:create, :update, :destroy]
  
  resources :users, only: [:new, :create, :edit, :update, :destroy, :index]
  get    '/users/admin' => 'users#admin_index', as: 'users_admin'
  get    '/user/confirm/:token' => 'users#confirm_email', as: 'user_email_confirmation'
  patch    '/user/lu/:id' => 'users#limited_update', as: 'user_limited_update'

  get    '/distributor/edit' => 'distributors#edit', as: 'distributor'
  get    '/distributor/full_profile' => 'distributors#full_profile', as: 'distributor_full_profile'
  patch  '/distributor/edit' => 'distributors#update'
  patch  '/distributor_brands' => 'distributor_brands#update'
  patch  '/distributor/adminupdate/:id' => 'distributors#adminupdate', as: 'distributor_admin_update'
  delete '/distributor/validation/delitem' => 'distributors#validation_delete', as: 'distributor_validation_delete'

  get    '/retailer/edit' => 'retailers#edit', as: 'retailer'
  get    '/retailer/full_profile' => 'retailers#full_profile', as: 'retailer_full_profile'
  patch  '/retailer/edit' => 'retailers#update'
  patch  '/retailer/adminupdate/:id' => 'retailers#adminupdate', as: 'retailer_admin_update'
  delete '/retailer/validation/delitem' => 'retailers#validation_delete', as: 'retailer_validation_delete'


  # v2 public view
  get    '/brands' => 'brands#index', as: 'brands'
  get    '/brands/s/' => 'brands#search', as: 'search_brands'
  get    '/brand/view/:id' => 'brands#view', as: 'view_brand'
  get    '/brand/preview/:id' => 'brands#preview', as: 'preview_brand'

  get    '/retailer/view/:id' => 'retailers#view', as: 'view_retailer'
  get    '/distributor/view/:id' => 'distributors#view', as: 'view_distributor'

  # for brand editing
  get    '/brand/edit' => 'brands#edit', as: 'brand'
  get    '/brand/full_profile' => 'brands#full_profile', as: 'brand_full_profile'
  patch  '/brand/edit' => 'brands#update'
  patch  '/brand/adminupdate/:id' => 'brands#adminupdate', as: 'brand_admin_update'
  get    '/brand/subscribe' => 'brands#subscription', as: 'brand_subscription'

  # for article brand link
  get    '/brands/list' => 'brands#list', as: 'brand_list'
  # for article product link
  get    '/products/list' => 'products#list', as: 'product_list'

  get '/onboard/distributor/one' => 'onboard_distributor#one', as: 'onboard_distributor_one'
  get '/onboard/distributor/two' => 'onboard_distributor#two', as: 'onboard_distributor_two'

app/views/shared/profileform/armor/_armor_account_details.html.erb
<div class="row">
	<div class="small-12 columns">
		<table class="armor-account-summary">
			<a name="a-armor-bank-info"></a>
			<tr><td colspan="2" style="text-align: center;"><h3>Your Armor Payments, a Payoneer Company, account information:</h3></td></tr>
			<tr><td class="fieldname darker">Account ID</td><td><%= c.armor_account_id %></td></tr>
			<tr><td class="fieldname darker">User ID</td><td><%= u.armor_user_id %></td></tr>
			<tr><td class="fieldname darker">Bank Info <br><br><em>Where’s my money? You must add in your bank account information to receive payment (Brands) or refunds (Retailers and Distributors).</em></td>
			<% if errors %>
				<td>
					<span class="error">
						Sorry, there was an error. Please reload the page.<br>
						<% errors.each do |m| %>
							<%= m %><br>
						<% end %>
					</span>
				</td>
			<% else %>
				<td colspan="2"><a id="bankInstructionsFrame-lightbox-preview" data-url="<%= url %>" class="landing-button">Add Bank Info</a></td>
			<% end %>
			</tr>

			<tr><td class="fieldname">Company Name</td><td><%= c.company_name %></td></tr>
			<tr><td class="fieldname">User Name</td><td><%= u.contact.firstname %> <%=u.contact.lastname %></td></tr>
			<tr><td class="fieldname">Email</td> <td><%= u.email %></td></tr>
			<tr><td class="fieldname">Phone</td><td><%= u.contact.phone.phony_formatted(format: :international , spaces: '-') %></td></tr>
			<tr><td class="fieldname">Address</td> <td><%= c.address.address1 %><%= ", #{c.address.address2}" %></td></tr>
			<tr><td class="fieldname">City/Town/Department</td> <td><%= c.address.city %></td></tr>
			<tr><td class="fieldname">State/Province/Region/County</td> <td><%= c.address.state_2 %></td></tr>
			<tr><td class="fieldname">Zip/Postal Code</td> <td><%= c.address.postcode %></td></tr>
			<tr><td class="fieldname">Country</td> <td><%= c.address.country_2 %></td></tr>
		</table>
	</div><!--/.small-12-->
</div><!--/.row-->
<br><br>

	<% content_for :javascript_foot do %>
		<script type="text/javascript">
			var ArmorInstructionsClicked = false;
			$("#bankInstructionsFrame-lightbox-preview").click(function(){
				if (!ArmorInstructionsClicked) {
					var url = $(this).attr("data-url");
					showArmorPaymentsLightboxUi(url, 250, true);
					ArmorInstructionsClicked = true;
				} else {
					$('#order-item-data').html("<div class='text-center'><h3>Sorry, the link has expired. Reloading page...</h3></div>");
					$('.overlay#order-item-overlay').fadeIn();
					$('#order-item').fadeIn();
					window.location.replace('<%= eval("#{u.company_type.downcase}_url") + "#a-armor" %>');
					window.location.reload(true);
				}
			});
		</script>
	<% end %>

app/views/shared/profileform/armor/_armor_combined_form.html.erb
<div class="row">
	<div class="small-12 columns">
		<% if c.class.to_s == "Brand" %>
			<h2>Enable Armor Payments (Payoneer) Escrow</h2>
			<h3>In order to use Armor Payments (Payoneer) Escrow you will need to complete these profile items. These fields can be updated via the form below or via the <%= link_to "Company Info", '#a-companyinfo' %> or <%= link_to "Your Login Info", '#a-login-info' %> sections on this page.</h3>
		<% else %>
			<h2>Enable Ordering</h2>
			<h3>In order to submit orders you will need to complete these profile items. These fields can be updated via the form below or via the <%= link_to "Company Info", '#a-companyinfo' %> or <%= link_to "Your Login Info", '#a-login-info' %> sections on this page.</h3>
		<% end %>
	</div><!--/.small-12-->
</div><!--/.row-->

<div class="row">
	<div class="small-12 columns">
		<div class="panel" style="background-color: #f2f2f2;">
			<% if m.present? %>
				<h3>Please enter the following:</h3>
				<ul style="font-weight: 100;">
				<% m.each do |err| %>
					<% if err == "Phone" %>
						<li><%= err %><%= flash[:error] ? " <span style='color: red;'>(#{flash[:error]})</span>".html_safe : "" %></li>
					<% else %>
						<li><%= err %></li>
					<% end %>
				<% end %>
				</ul>
			<% end %>
			<% if e.present? %>
				<h3>Please fix the following:</h3>
				<ul style="font-weight: 100;">
				<% e.each do |k,v| %>
					<li><%= v %></li>
				<% end %>
			<% end %>
			</ul>
		</div>
	</div><!--/.small-12-->
</div><!--/.row-->

<%= form_tag ap_complete_required_url, method: "post", id: "armor-combined" do %>
<div class="row">
	<div class="small-12 columns">
		<hr>
		<h2><small>from</small> Company Info</h2>
	</div><!--/.small-12-->
</div><!--/.row-->
<div class="row">
	<div class="small-12 columns">
	<%= label_tag :company_name, "Company Name", class: ( m.include?("Company Name") ? "error" : nil) %>
	<%= text_field_tag :company_name, c.company_name, placeholder: "Company Name", class: ( m.include?("Company Name") ? "error" : nil) %>
	</div><!--/.small-12-->
</div><!--/.row-->
<div class="row">
	<div class="small-12 columns">
	<%= label_tag :address1, "Address 1", class: ( m.include?("Address") ? "error" : nil) %>
	<%= text_field_tag :address1, c.address.address1, placeholder: "Address 1", class: ( m.include?("Address") ? "error" : nil) %>
	<%= label_tag :address2, "Address 2 (optional)" %>
	<%= text_field_tag :address2, c.address.address2, placeholder: "Address 2" %>
	</div><!--/.small-12-->
</div><!--/.row-->
<div class="row">
	<div class="medium-6 columns">
	<%= label_tag :city, "City/Town/Department", class: ( m.include?("City/Town/Department") ? "error" : nil) %>
	<%= text_field_tag :city, c.address.city, placeholder: "City/Town/Department", class: ( m.include?("City/Town/Department") ? "error" : nil) %>
	</div><!--/.medium-6-->
	<div class="medium-6 columns">
	<%= label_tag :state, "State/Province/Region/County", class: ( (m.include?("State/Provice/Region/County") || e[:state]) ? "error" : nil) %>
	<%= text_field_tag :state, c.address.state, placeholder: "State/Province/Region/County", class: ( (m.include?("State/Provice/Region/County") || e[:state]) ? "error" : nil) %>
	</div><!--/.medium-6-->
</div><!--/.row-->
<div class="row">
	<div class="medium-4 columns">
	<%= label_tag :postcode, "Zip/Postcode", class: ( m.include?("Zip/Postcode") ? "error" : nil)  %>
	<%= text_field_tag :postcode, c.address.postcode, placeholder: "Zip/Postcode", class: ( m.include?("Zip/Postcode") ? "error" : nil)  %>
	</div><!--/.medium-4-->
	<div class="medium-8 columns">
	<%= label_tag :country, "Country", class: ( (m.include?("Country") || e[:country]) ? "error" : nil)  %>
	<%= text_field_tag :country, c.address.country, placeholder: "Country", class: ( (m.include?("Country") || e[:country])  ? "error country-autocomplete" : "country-autocomplete")  %>
	</div><!--/.medium-8-->
</div><!--/.row-->
<div class="row">
	<div class="small-12 columns">
		<hr>
		<h2><small>from</small> Your Login Info</h2>
	</div><!--/.small-12-->
</div><!--/.row-->
<div class="row">
	<div class="medium-4 columns">
	<%= label_tag :user_firstname, "First Name", class: ( m.include?("First Name") ? "error" : nil) %>
	<%= text_field_tag :user_firstname, u.contact.firstname, placeholder: "First Name", class: ( m.include?("First Name") ? "error" : nil) %>
	</div><!--/.medium-4-->
	<div class="medium-4 columns">
	<%= label_tag :user_lastname, "Last Name", class: ( m.include?("Last Name") ? "error" : nil) %>
	<%= text_field_tag :user_lastname, u.contact.lastname, placeholder: "Last Name", class: ( m.include?("Last Name") ? "error" : nil) %>
	</div><!--/.medium-4-->
	<div class="medium-4 columns">
	<%= label_tag :user_phone, "Phone", class: ( m.include?("Phone") || flash[:error] ? "error" : nil) %>
	<%= text_field_tag :user_phone, u.contact.phone.present? ? u.contact.phone.phony_formatted(format: :international , spaces: '-') : "", placeholder: "Phone", class: ( m.include?("Phone") || flash[:error] ? "error" : nil) %>
	</div><!--/.medium-4-->
</div><!--/.row-->
<div class="row">
	<div class="small-12 columns text-right">
		<hr>
		<%= submit_tag :Update, class: "landing-button" %>
	</div><!--/.small-12-->
</div><!--/.row-->
<% end %>

app/views/shared/profileform/armor/_armor_ordering_and_payments.html.erb
<br>
<a class="anchor" id="a-ordering-and-payments"></a>
<% if company.disable_armor_payments %>	
<div class="panel text-center" style="background-color: #f2f2f2;"><h3><strong>Armor Payments (Payoneer) is <span style="color:red;">OFF</span>.</strong></h3></div>
<% end %>
<div class="row">
	<div class="small-12 columns text-center">
		<%= image_tag "https://s3.amazonaws.com/landingintl-us/general/payoneer.png", width: "600"%>
	</div>
</div>


<div class="row">
	<div class="small-12 columns">
		<a class="anchor" id="a-armor"></a>
	</div><!--/.small-12-->
</div><!--/.row-->

<% unless @current_user.company.disable_armor_payments %>

<% allow, missing, errors = @current_user.allows_armor_signup %>
<% if @current_user.company.armor_account_id %>
	
	<div class="row">
		<div class="small-12 columns">
			<hr>
			<h2>Armor Payments (Payoneer) Escrow Enabled</h2>

			<h3>You are now able to complete transactions via Armor Payments (Payoneer) and can now 
				<% if @current_user.company_type == "Brand" %>
					sell your products on the Landing International platform.
				<% else %>
					order products from our <%= link_to "Brand Partners", brands_url %>
				<% end %>
			</h3>
			
			<div class="landing-notice">In order to receive payment (for Brands) or refunds (for Retailers and Distributors), you need to ensure that Armor Payments (Payoneer) has your bank account information. Order payment and processing may be delayed if your banking information is incomplete. <a href="#a-armor-bank-info">You can submit your bank account information to Armor/Payoneer below.</a></div>

			<% if company.errors.any? %>
				<%= render partial: 'shared/profileform/armor/armor_account_details', locals: { c: company, u: @current_user.company.users.with_armor_user_id.first, url: nil, errors: company.errors.full_messages } %>
			<% elsif @armor_bank_url.present? %>
				<%= render partial: 'shared/profileform/armor/armor_account_details', locals: { c: company, u: @current_user.company.users.with_armor_user_id.first , url: @armor_bank_url, errors: nil } %>
			<% end %>

			

		</div><!--/.small-12-->
	</div><!--/.row-->

<% elsif @current_user.company.armor_account_id.blank? && allow %>
	<%= render partial: 'shared/profileform/armor/armor_signup', locals: { c: @current_user.company, u: @current_user } %>
<% else %>
	<%= render partial: 'shared/profileform/armor/armor_combined_form', locals: { c: @current_user.company, u: @current_user, m: missing, e: errors } %>
<% end %>

<% end %>

app/views/shared/profileform/armor/_armor_signup.html.erb
<% unless c.disable_armor_payments %>
	<div class="row">
		<div class="small-12 columns">
			<hr>
			<h2>Enable Armor Payments (Payoneer) Escrow</h2>
			<h3><strong> Accept Armor Payments (Payoneer) Terms and Conditions below to enable.</strong></h3>
			<div class="landing-notice"><h3>Companies domiciled in Arizona or Idaho are currently unable to use Armor Payments due to escrow licensing issues. You will be unable to use Armor Payments (Payoneer) Escrow service if your company is headquartered in either of those states.</h3></div>
		</div><!--/.small-12-->
	</div><!--/.row-->

	<div class="row">
		<div class="small-12 columns">
			<% if flash[:error] %>
				<div class="row">
					<div class="small-12 columns">
						<br>
						<span class="error"><%= flash[:error] %><br>
							<% if flash[:errorlist] %>
								<% flash[:errorlist].each do |error| %>
									<%= error %><br>
								<% end %>
							<% end %>
						</span>
					</div><!--/.small-12-->
				</div><!--/.row-->
			<% end %>
			<table class="armor-account-summary">
				<tr><td colspan="2"><h3>You will be sharing the following information with Armor Payments (Payoneer):</h3></td></tr>
				<tr><td class="fieldname">Company Name</td><td><%= c.company_name %></td></tr>
				<tr><td class="fieldname">User Name</td><td><%= u.contact.firstname %> <%=u.contact.lastname %></td></tr>
				<tr><td class="fieldname">Email</td> <td><%= u.email %></td></tr>
				<tr><td class="fieldname">Phone</td><td><%= u.contact.phone.phony_formatted(format: :international , spaces: '-') %></td></tr>
				<tr><td class="fieldname">Address</td> <td><%= c.address.address1 %><%= ", #{c.address.address2}" %></td></tr>
				<tr><td class="fieldname">City/Town/Department</td> <td><%= c.address.city %></td></tr>
				<tr><td class="fieldname">State/Province/Region/County</td> <td><%= c.address.state_2 %></td></tr>
				<tr><td class="fieldname">Zip/Postal Code</td> <td><%= c.address.postcode %></td></tr>
				<tr><td class="fieldname">Country</td> <td><%= c.address.country_2 %></td></tr>
			</table>
		</div><!--/.small-12-->
	</div><!--/.row-->
	<br>
	<div class="row">
		<div class="small-12 columns text-right">
		<%= form_tag ap_create_account_url + "#a-armor", method: "post", id: "armor-signup" do %>
			<%= render 'shared/profileform/armor/armor_signup_form' %>
			<%= submit_tag "Enable Armor Payments (Payoneer) Escrow", class: "landing-button" %>
		<% end %>
		</div><!--/.small-12-->
	</div><!--/.row-->
<% end %>

app/views/shared/profileform/armor/_armor_signup_form.html.erb
	<input type="checkbox" id="armor_payments_terms" name="armor_payments_terms" class="error"/>
	<!-- Replace 1052419 with your own Partner ID in this URL --> 
	<label for="armor_payments_terms"><span style="font-weight: 200; font-size: 0.75em;">I agree to the Armor Payments, a Payoneer company, <a href="https://app.armorpayments.com/terms/160405182787" target="_BLANK">Terms and Conditions</a>.</span></label>